[jobs] Update from codeready-workspaces/crw-jenkins @ 1f15
Signed-off-by: Red Hat Devstudio Release Bot <nickboldt+devstudio-release@gmail.com>

diff --git a/crw-jenkins/jobs/CRW_CI/crw-pluginregistry_2.10.jenkinsfile b/crw-jenkins/jobs/CRW_CI/crw-pluginregistry_2.10.jenkinsfile
--- a/crw-jenkins/jobs/CRW_CI/crw-pluginregistry_2.10.jenkinsfile
+++ b/crw-jenkins/jobs/CRW_CI/crw-pluginregistry_2.10.jenkinsfile
@@ -6,21 +6,22 @@ import groovy.transform.Field
 // def FORCE_BUILD = "false"
 // MIDSTM_BRANCH
 
-// TODO source from eclipse/che-devfile-registry too
+///// ///// ///// ///// ///// ///// ///// ///// ///// ///// ///// ///// ///// ///// 
+///// THIS FILE IS DEPRECATED and not used; for 2.9+, see template_2.x.jenkinsfile
+///// ///// ///// ///// ///// ///// ///// ///// ///// ///// ///// ///// ///// ///// 
 
 def MIDSTM_REPO = "redhat-developer/codeready-workspaces" //source repo from which to find and sync commits to pkgs.devel repo
 def DWNSTM_REPO = "redhat-developer/codeready-workspaces-images" // dist-git repo to use as target
 def DWNSTM_BRANCH = MIDSTM_BRANCH // target branch in dist-git repo, eg., crw-2.y-rhel-8
-def SYNC_REPO = "devfileregistry" // also used for the Brew dockerfile params
+def SYNC_REPO = "pluginregistry" // also used for the Brew dockerfile params
 def USE_DIGESTS = "true" // if true, use @sha256:digest in registry; if false, use :tag
-def SYNC_FILES="arbitrary-users-patch build devfiles images .gitignore .htaccess LICENSE README.md VERSION"
 
 def OLD_SHA_MID=""
 def OLD_SHA_DWN=""
 def NEW_SHA_MID=""
 def NEW_SHA_DWN=""
 
-def buildNode = "rhel8" // node label
+def buildNode = "rhel8||s390x-rhel8||ppc64le-rhel8" // node label(s)
 timeout(120) {
   node("${buildNode}"){ stage "Sync repos"
     wrap([$class: 'TimestamperBuildWrapper']) {
@@ -33,15 +34,15 @@ timeout(120) {
       util.installRhpkg()
       withCredentials([string(credentialsId:'crw_devstudio-release-token', variable: 'GITHUB_TOKEN'),
           file(credentialsId: 'crw_crw-build-keytab', variable: 'CRW_KEYTAB')]) {
-        util.bootstrap(CRW_KEYTAB)
 
         println "########################################################################################################"
         println "##  Clone and update github.com/${MIDSTM_REPO}.git"
         println "########################################################################################################"
-        util.cloneRepo("https://github.com/${MIDSTM_REPO}.git", "${WORKSPACE}/targetmid", MIDSTM_BRANCH)
+        util.cloneRepoWithBootstrap("https://github.com/${MIDSTM_REPO}.git", "${WORKSPACE}/targetmid", MIDSTM_BRANCH, true)
         OLD_SHA_MID = util.getLastCommitSHA("${WORKSPACE}/targetmid")
         println "Got OLD_SHA_MID in targetmid folder: " + OLD_SHA_MID
-        SOURCE_DIR="${WORKSPACE}/targetmid/dependencies/che-devfile-registry/"
+        SOURCE_DIR="${WORKSPACE}/targetmid/dependencies/che-plugin-registry/"
+
         util.updateBaseImages(SOURCE_DIR + "build/dockerfiles", DWNSTM_BRANCH)
         NEW_SHA_MID = util.getLastCommitSHA("${WORKSPACE}/targetmid")
         println "Got NEW_SHA_MID in targetmid folder: " + NEW_SHA_MID
@@ -49,29 +50,17 @@ timeout(120) {
         println "########################################################################################################"
         println "##  Sync ${SYNC_REPO} to codeready-workspaces-images"
         println "########################################################################################################"
-        util.cloneRepo("https://github.com/${DWNSTM_REPO}", "${WORKSPACE}/targetdwn", DWNSTM_BRANCH)
+        util.cloneRepoWithBootstrap("https://github.com/${DWNSTM_REPO}", "${WORKSPACE}/targetdwn", DWNSTM_BRANCH, false)
         OLD_SHA_DWN = util.getLastCommitSHA("${WORKSPACE}/targetdwn")
         println "Got OLD_SHA_DWN in targetdwn folder: " + OLD_SHA_DWN
         TARGET_DIR="${WORKSPACE}/targetdwn/" + util.getCRWLongName(SYNC_REPO) + "/"
 
         // rsync files to codeready-workspaces-images
         sh('''#!/bin/bash -xe
-          SOURCEDIR="''' + SOURCE_DIR + '''"
-          TARGETDIR="''' + TARGET_DIR + '''"
-          SYNC_FILES="''' + SYNC_FILES + '''"
-          [ ! -d ${TARGETDIR} ] && mkdir -p ${TARGETDIR}
-          for d in ${SYNC_FILES}; do
-            if [[ -f ${SOURCEDIR}/${d} ]]; then
-              rsync -azrlt ${SOURCEDIR}/${d} ${TARGETDIR}/${d}
-            elif [[ -d ${SOURCEDIR}/${d} ]]; then
-              # copy over the dir contents
-              rsync -azrlt ${SOURCEDIR}/${d}/* ${TARGETDIR}/${d}/
-              # sync the directory and delete from targetdwn if deleted from source
-              rsync -azrlt --delete ${SOURCEDIR}/${d}/ ${TARGETDIR}/${d}/
-            else
-              echo "[WARN] Could not find ${SOURCEDIR}/${d} to sync to ${TARGETDIR}/${d}"
-            fi
-          done
+SOURCEDIR="''' + SOURCE_DIR + '''"
+TARGETDIR="''' + TARGET_DIR + '''"
+[ ! -d ${TARGETDIR} ] && mkdir -p ${TARGETDIR}
+rsync -azrlt --delete ${SOURCEDIR} ${TARGETDIR}
         ''')
 
         sh('''#!/bin/bash -xe
@@ -79,9 +68,6 @@ timeout(120) {
           CRW_VERSION="''' + CRW_VERSION_F + '''"
           # apply patches to transform CRW upstream to pkgs.devel version
           sed -i ''' + TARGET_DIR + '''Dockerfile --regexp-extended \
-            `# Replace image used for registry with rhel8/httpd-24` \
-            -e 's|^ *FROM registry.access.redhat.com/.* AS registry|# &|' \
-            -e 's|# *(FROM.*rhel8/httpd.*)|\\1|' \
             `# Strip registry from image references` \
             -e 's|FROM registry.access.redhat.com/|FROM |' \
             -e 's|FROM registry.redhat.io/|FROM |' \
@@ -99,14 +85,11 @@ timeout(120) {
             -e 's|^ *FROM registry AS offline-registry|# &|' \
             -e '/^ *FROM builder AS offline-builder/,+3 s|.*|# &|' \
             -e 's|^[^#]*--from=offline-builder.*|# &|' \
-            -e '/COPY --from=builder/a COPY --from=builder /build/resources /var/www/html/resources' \
-            `# Enable cache_projects.sh` \
+            `# Enable cache_artifacts.sh` \
             -e '\\|swap_images.sh|i # Cache projects in CRW \\
-COPY ./build/dockerfiles/rhel.cache_projects.sh resources.tgz /tmp/ \\
-RUN /tmp/rhel.cache_projects.sh /build/ && rm -rf /tmp/rhel.cache_projects.sh /tmp/resources.tgz \\
-' \
-            `# Enable swap in arch specific devfiles` \
-            -e '\\|swap_images.sh|i RUN ./swap_yamlfiles.sh devfiles' \
+COPY ./build/dockerfiles/rhel.cache_artifacts.sh resources.tgz /tmp/ \\
+RUN /tmp/rhel.cache_artifacts.sh /build/v3/ && rm -rf /tmp/rhel.cache_artifacts.sh /tmp/resources.tgz \\
+'
 
           METADATA='ENV SUMMARY="Red Hat CodeReady Workspaces ''' + SYNC_REPO + ''' container" \\\r
     DESCRIPTION="Red Hat CodeReady Workspaces ''' + SYNC_REPO + ''' container" \\\r
@@ -133,18 +116,17 @@ LABEL summary="$SUMMARY" \\\r
         // push changes to codeready-workspaces-images
         util.updateBaseImages(TARGET_DIR, DWNSTM_BRANCH, "--nocommit")
         sh('''#!/bin/bash -xe
-          SYNC_FILES="''' + SYNC_FILES + '''"
-          cd ${WORKSPACE}/targetdwn
-          git add ''' + util.getCRWLongName(SYNC_REPO) + '''
-          git update-index --refresh || true # ignore timestamp updates
-          if [[ \$(git diff-index HEAD --) ]]; then # file changed
-            cd ''' + TARGET_DIR + '''
-            git add Dockerfile ${SYNC_FILES} . -A -f
-            # note this might fail if we're syncing from a tag vs. a branch
-            git commit -s -m "[sync] Update from ''' + MIDSTM_REPO + ''' @ ''' + NEW_SHA_MID + '''" Dockerfile ${SYNC_FILES} . || true
-            git push origin ''' + DWNSTM_BRANCH + ''' || true
-            echo "[sync] Updated pkgs.devel @ \$(git rev-parse --short=4 HEAD) from ''' + MIDSTM_REPO + ''' @ ''' + NEW_SHA_MID + '''"
-          fi
+cd ${WORKSPACE}/targetdwn
+git add ''' + util.getCRWLongName(SYNC_REPO) + '''
+git update-index --refresh || true # ignore timestamp updates
+if [[ \$(git diff-index HEAD --) ]]; then # file changed
+  cd ''' + TARGET_DIR + '''
+  git add Dockerfile . -A -f
+  # note this might fail if we're syncing from a tag vs. a branch
+  git commit -s -m "[sync] Update from ''' + MIDSTM_REPO + ''' @ ''' + NEW_SHA_MID + '''" Dockerfile . || true
+  git push origin ''' + DWNSTM_BRANCH + ''' || true
+  echo "[sync] Updated pkgs.devel @ \$(git rev-parse --short=4 HEAD) from ''' + MIDSTM_REPO + ''' @ ''' + NEW_SHA_MID + '''"
+fi
         ''')
 
         NEW_SHA_DWN = util.getLastCommitSHA("${WORKSPACE}/targetdwn")
@@ -156,7 +138,7 @@ LABEL summary="$SUMMARY" \\\r
         }
 
         println "########################################################################################################"
-        println "##  Kickoff Sync to downstream job"
+        println "##  Trigger sync to downstream job"
         println "########################################################################################################"
         if (!OLD_SHA_MID.equals(NEW_SHA_MID) || !OLD_SHA_DWN.equals(NEW_SHA_DWN) || FORCE_BUILD == "true") {
           JOB_BRANCH = util.getJobBranch(MIDSTM_BRANCH)
diff --git a/crw-jenkins/jobs/CRW_CI/crw-theia-containers_2.10.jenkinsfile b/crw-jenkins/jobs/CRW_CI/crw-theia-containers_2.10.jenkinsfile
--- a/crw-jenkins/jobs/CRW_CI/crw-theia-containers_2.10.jenkinsfile
+++ b/crw-jenkins/jobs/CRW_CI/crw-theia-containers_2.10.jenkinsfile
@@ -1,3 +1,7 @@
+///// ///// ///// ///// ///// ///// ///// ///// ///// ///// ///// ///// ///// ///// 
+///// THIS FILE IS DEPRECATED and not used; for 2.9+, just use crw-theia-sources
+///// ///// ///// ///// ///// ///// ///// ///// ///// ///// ///// ///// ///// ///// 
+
 #!/usr/bin/env groovy
 
 import groovy.transform.Field
@@ -19,7 +23,7 @@ def SOURCE_SHA=""
 def assetPath="/lastSuccessfulBuild/artifact/crw-theia/dockerfiles/*zip*/dockerfiles.zip"
 def List req_platforms = PLATFORMS.tokenize(",").collect { it.trim() }
 
-def String nodeLabel = 'rhel8'
+def String nodeLabel = 'rhel8||s390x-rhel8||ppc64le-rhel8'
 timeout(120) {
   node(nodeLabel) {
     stage ("Sync repos on ${nodeLabel}") {
@@ -45,32 +49,20 @@ curl -sSLI ''' + jenkinsURL + '''/lastSuccessfulBuild/artifact/crw-theia/dockerf
 
           withCredentials([string(credentialsId:'crw_devstudio-release-token', variable: 'GITHUB_TOKEN'),
               file(credentialsId: 'crw_crw-build-keytab', variable: 'CRW_KEYTAB')]) {
-            util.bootstrap(CRW_KEYTAB)
-            util.cloneRepo(MIDSTM_REPO, "crw-theia", MIDSTM_BRANCH)
+            util.cloneRepoWithBootstrap(MIDSTM_REPO, "crw-theia", MIDSTM_BRANCH, true)
 
-            println("Retrieve dockerfiles from build and extract in crw-theia")
-            sh('''#!/bin/bash +x
-              cd ${WORKSPACE}/crw-theia
-              curl -sSLO "''' + jenkinsURL + assetPath + '''"
-              if [[ -f dockerfiles.zip ]]; then
-                unzip -o dockerfiles.zip
-                rm dockerfiles.zip
-              else 
-                echo "Error downloading ''' + jenkinsURL + assetPath + ''' !"
-                exit 1
-              fi
-              ''')
             SOURCE_SHA = util.getLastCommitSHA("${WORKSPACE}/crw-theia")
             println "Got SOURCE_SHA in crw-theia folder: " + SOURCE_SHA
 
-            util.cloneRepo(DWNSTM_REPO1, "target1", MIDSTM_BRANCH)
-            util.cloneRepo(DWNSTM_REPO2, "target2", MIDSTM_BRANCH)
-            util.cloneRepo(DWNSTM_REPO3, "target3", MIDSTM_BRANCH)
+            util.cloneRepoWithBootstrap(DWNSTM_REPO1, "target1", MIDSTM_BRANCH, false)
+            util.cloneRepoWithBootstrap(DWNSTM_REPO2, "target2", MIDSTM_BRANCH, false) 
+            util.cloneRepoWithBootstrap(DWNSTM_REPO3, "target3", MIDSTM_BRANCH, false)
             OLD_SHA1 = util.getLastCommitSHA("${WORKSPACE}/target1")
             OLD_SHA2 = util.getLastCommitSHA("${WORKSPACE}/target2")
             OLD_SHA3 = util.getLastCommitSHA("${WORKSPACE}/target3")
 
-            println("Sync Changes and do Dockerfile transformations")
+            // TODO CRW-1609 we should only have to copy from lower midstream (crw-images) to downstream (pkgs.devel)
+            println("Sync upper midstream (crw-theia) to downstream (pkgs.devel)")
             sh('''#!/bin/bash -xe
               for targetN in target1 target2 target3; do
                 if [[ \$targetN == "target1" ]]; then SRC_PATH="${WORKSPACE}/crw-theia/dockerfiles/theia-dev"; fi
@@ -89,54 +81,18 @@ curl -sSLI ''' + jenkinsURL + '''/lastSuccessfulBuild/artifact/crw-theia/dockerf
                   fi
                 done
 
-                # apply changes from upstream Dockerfile to downstream Dockerfile
-                find ${SRC_PATH} -name "*ockerfile*" || true
+                # sync upstream Dockerfiles to downstream Dockerfiles
                 SOURCEDOCKERFILE="${SRC_PATH}/Dockerfile"
                 TARGETDOCKERFILE=""
                 if [[ \$targetN == "target1" ]]; then TARGETDOCKERFILE="${WORKSPACE}/target1/Dockerfile"; fi
                 if [[ \$targetN == "target2" ]]; then TARGETDOCKERFILE="${WORKSPACE}/target2/Dockerfile"; fi
                 if [[ \$targetN == "target3" ]]; then TARGETDOCKERFILE="${WORKSPACE}/target3/Dockerfile"; fi
-
-                # apply generic patches to convert source -> target dockerfile (for use in Brew)
-                if [[ ${SOURCEDOCKERFILE} != "" ]] && [[ -f ${SOURCEDOCKERFILE} ]] && [[ ${TARGETDOCKERFILE} != "" ]]; then
-                  sed ${SOURCEDOCKERFILE} -r \
-                  `# cannot resolve RHCC from inside Brew so use no registry to resolve from Brew using same container name` \
-                  -e "s#FROM registry.redhat.io/#FROM #g" \
-                  -e "s#FROM registry.access.redhat.com/#FROM #g" \
-                  `# cannot resolve quay from inside Brew so use internal mirror w/ revised container name` \
-                  -e "s#quay.io/crw/#registry-proxy.engineering.redhat.com/rh-osbs/codeready-workspaces-#g" \
-                  `# cannot resolve theia-rhel8:next, theia-dev-rhel8:next from inside Brew so use revised container tag` \
-                  -e "s#(theia-.+):next#\\1:''' + CRW_VERSION + '''#g" \
-                  > ${TARGETDOCKERFILE}
+                if [[ ${SOURCEDOCKERFILE} != "" ]] && [[ -f ${SOURCEDOCKERFILE} ]]; then
+                  cp ${SOURCEDOCKERFILE} ${TARGETDOCKERFILE}
                 else
-                  echo "[WARNING] ${SOURCEDOCKERFILE} does not exist, so cannot sync to ${TARGETDOCKERFILE}"
+                  echo "[ERROR] ${SOURCEDOCKERFILE} does not exist, so cannot sync to ${TARGETDOCKERFILE}"
+                  exit 1
                 fi
-
-                # add special patches to convert theia bootstrap build into brew-compatible one
-                # TODO should this be in build.sh instead?
-                if [[ \$targetN == "target2" ]] && [[ ${TARGETDOCKERFILE} != "" ]]; then
-                  sed -r \
-                  `# fix up theia loader patch inclusion (3 steps)` \
-                  -e "s#ADD branding/loader/loader.patch .+#COPY asset-branding.tar.gz /tmp/asset-branding.tar.gz#g" \
-                  -e "s#ADD (branding/loader/CodeReady_icon_loader.svg .+)#RUN tar xvzf /tmp/asset-branding.tar.gz -C /tmp; cp /tmp/\\1#g" \
-                  -e "s#(RUN cd .+/theia-source-code && git apply).+#\\1 /tmp/branding/loader/loader.patch#g" \
-                  `# don't create tarballs` \
-                  -e "s#.+tar zcf.+##g" \
-                  `# don't do node-gyp installs, etc.` \
-                  -e "s#.+node-gyp.+##g" \
-                  `# copy from builder` \
-                  -e "s#^COPY branding #COPY --from=builder /tmp/branding #g" \
-                  -i ${TARGETDOCKERFILE}
-                fi
-
-                # update platforms in container.yaml
-                platforms="''' + req_platforms.join(' ') + '''"
-                cd ${WORKSPACE}/${targetN}
-                yq -iy '.platforms.only |= ([])' container.yaml
-                for platform in $platforms ; do
-                  echo "Add platform = $platform to ${WORKSPACE}/${targetN}/container.yaml"
-                  yq -iy '.platforms.only |= (.+ ["'$platform'"] | unique)' container.yaml
-                done
               done
             ''')
 
@@ -156,12 +112,11 @@ curl -sSLI ''' + jenkinsURL + '''/lastSuccessfulBuild/artifact/crw-theia/dockerf
                     fi
                   done
                   git add Dockerfile
-                  git add container.yaml
                   git commit -s -m "[sync] Update from ''' + MIDSTM_REPO + ''' @ ''' + SOURCE_SHA + '''" || true
                   git push origin ''' + MIDSTM_BRANCH + ''' || true
                 fi
               done
-              ''')
+            ''')
             util.updateBaseImages("${WORKSPACE}/target1", MIDSTM_BRANCH, "-q")
             util.updateBaseImages("${WORKSPACE}/target2", MIDSTM_BRANCH, "-q")
             util.updateBaseImages("${WORKSPACE}/target3", MIDSTM_BRANCH, "-q")
diff --git a/crw-jenkins/jobs/CRW_CI/sync-to-downstream_2.10.jenkinsfile b/crw-jenkins/jobs/CRW_CI/sync-to-downstream_2.10.jenkinsfile
--- a/crw-jenkins/jobs/CRW_CI/sync-to-downstream_2.10.jenkinsfile
+++ b/crw-jenkins/jobs/CRW_CI/sync-to-downstream_2.10.jenkinsfile
@@ -13,25 +13,37 @@ def String SOURCE_REPO = "redhat-developer/codeready-workspaces-images" // sourc
 def OLD_SHA=""
 def NEW_SHA=""
 def SOURCE_SHA=""
-def String nodeLabel = 'rhel8'
-timeout(180) {
+
+// NOTE: Yarn 2 + s390x = fail, so if build requires Yarn 2, don't run on s390x boxes, eg., REPOS.contains("-my-yarn2-project") ...
+def String nodeLabel = 'rhel8||s390x-rhel8||ppc64le-rhel8'
+
+timeout(300) {
   node(nodeLabel) {
     stage ("Sync repos on ${nodeLabel}") {
       wrap([$class: 'TimestamperBuildWrapper']) {
         sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/' + MIDSTM_BRANCH + '/product/util.groovy')
         def util = load "${WORKSPACE}/util.groovy"
         cleanWs()
+        currentBuild.description="Install skopeo and rhpkg;<br/> "
         util.installSkopeoFromContainer("")
         util.installRhpkg()
-        currentBuild.description=""
+        // install node and yarn if versions defined (eg., for theia-dev's generator tgz)
+        if (util.globalVar({nodeVersion})?.trim() && util.globalVar({yarnVersion})?.trim()) {
+          if (REPOS.contains("-theia-dev") || REPOS.contains("-dashboard")) { // need make, c++ for node-gyp
+            currentBuild.description+="install node, yarn, make, c++, node-gyp;<br/> "
+            util.installNPM(util.globalVar({nodeVersion}), util.globalVar({yarnVersion}), false, true)
+          } else {
+            currentBuild.description+="install node, yarn;<br/> "
+            util.installNPM(util.globalVar({nodeVersion}), util.globalVar({yarnVersion}), false, false)
+          }
+        }
 
           withCredentials([string(credentialsId:'crw_devstudio-release-token', variable: 'GITHUB_TOKEN'),
               file(credentialsId: 'crw_crw-build-keytab', variable: 'CRW_KEYTAB')]) {
-            util.bootstrap(CRW_KEYTAB)
             println "########################################################################################################"
             println "##  Clone and update github.com/${SOURCE_REPO}.git"
             println "########################################################################################################"
-            util.cloneRepo("https://github.com/${SOURCE_REPO}.git", "${WORKSPACE}/sources", MIDSTM_BRANCH)
+            util.cloneRepoWithBootstrap("https://github.com/${SOURCE_REPO}.git", "${WORKSPACE}/sources", MIDSTM_BRANCH, false)
             CRW_VERSION = util.getCrwVersion(MIDSTM_BRANCH)
             JOB_BRANCH = util.getJobBranch(MIDSTM_BRANCH)
 
@@ -48,16 +60,27 @@ timeout(180) {
 
                 // only update individual subfolders so that optional UPDATE_BASE_IMAGES_FLAGS is respected
                 // (eg., for operator being locked to golang 1.13 instead of latest 1.14)
-                util.updateBaseImages("${WORKSPACE}/sources/" + SYNC_REPOS[i], MIDSTM_BRANCH, UPDATE_BASE_IMAGES_FLAGS)
+                util.updateBaseImages("${WORKSPACE}/sources/" + SYNC_REPOS[i], MIDSTM_BRANCH, util.globalVar({UPDATE_BASE_IMAGES_FLAGS}))
                 SOURCE_SHA = util.getLastCommitSHA("${WORKSPACE}/sources")
                 println "Got SOURCE_SHA in sources folder: " + SOURCE_SHA
 
                 println "########################################################################################################"
                 println "##  Sync [${SYNC_REPOS[i]}] to pkgs.devel"
                 println "########################################################################################################"
-                util.cloneRepo("ssh://crw-build@pkgs.devel.redhat.com/containers/${SYNC_REPOS[i]}", "${WORKSPACE}/targetdwn/${SYNC_REPOS[i]}", MIDSTM_BRANCH)
+                util.cloneRepoWithBootstrap("ssh://crw-build@pkgs.devel.redhat.com/containers/${SYNC_REPOS[i]}", "${WORKSPACE}/targetdwn/${SYNC_REPOS[i]}", MIDSTM_BRANCH, false)
 
-                sh('''rsync -avhz --checksum --delete --exclude .git/ ${WORKSPACE}/sources/''' + SYNC_REPOS[i] + '''/ ${WORKSPACE}/targetdwn/''' + SYNC_REPOS[i])
+                sh('''
+SOURCEDIR="${WORKSPACE}/sources/''' + SYNC_REPOS[i] + '''/"
+TARGETDIR="${WORKSPACE}/targetdwn/''' + SYNC_REPOS[i] + '''"
+echo ".github/
+.git/
+.gitattributes
+sources
+" > /tmp/rsync-excludes
+echo "Rsync ${SOURCEDIR} to ${TARGETDIR}"
+rsync -azrlt --checksum --exclude-from /tmp/rsync-excludes --delete ${SOURCEDIR}/ ${TARGETDIR}/
+rm -f /tmp/rsync-excludes
+                ''')
 
                 OLD_SHA = util.getLastCommitSHA("${WORKSPACE}/targetdwn/${SYNC_REPOS[i]}")
                 println "Got OLD_SHA in targetdwn/${SYNC_REPOS[i]} folder: " + OLD_SHA
@@ -73,23 +96,31 @@ timeout(180) {
                     git push origin ''' + MIDSTM_BRANCH + ''' || true
                   fi''')
 
-                // run get-sources-jenkins to ensure we have the latest sources (in case we clobbered a previous run) and update source repo
+                // run get-sources to ensure we have the latest sources (in case we clobbered a previous run) and update source repo
                 sh('''#!/bin/bash -xe
                   export KRB5CCNAME=/var/tmp/crw-build_ccache
                   cd ${WORKSPACE}/targetdwn/''' + SYNC_REPOS[i] + '''
-                  ./get-sources-jenkins.sh -n -p ''' + JOB_BRANCH + '''
+                  if [[ -f get-sources.sh ]]; then 
+                    ./get-sources.sh -n -p ''' + JOB_BRANCH + '''
+                  elif [[ -f get-sources-jenkins.sh ]]; then # old name
+                    ./get-sources-jenkins.sh -n -p ''' + JOB_BRANCH + '''
+                  else 
+                    echo "[ERROR] Could not run get-sources.sh or get-sources-jenkins.sh!"; exit 1
+                  fi
                   COMMIT_SHA="$(git log origin/''' + MIDSTM_BRANCH + '''..''' + MIDSTM_BRANCH + ''' --pretty=format:%H)"
                   COMMIT_MSG="$(git log origin/''' + MIDSTM_BRANCH + '''..''' + MIDSTM_BRANCH + ''' --pretty=format:%B)"
                   if [ ! -z "$COMMIT_SHA" ] ; then
                     for f in $(git diff-tree --no-commit-id --name-only -r "$COMMIT_SHA") ; do
-                      cp $f ${WORKSPACE}/sources/''' + SYNC_REPOS[i] + '''
+                      cp ${f} ${WORKSPACE}/sources/''' + SYNC_REPOS[i] + '''/${f}
                     done
+                    git pull origin ''' + MIDSTM_BRANCH + ''' || true
                     git push origin ''' + MIDSTM_BRANCH + ''' || true
 
-                    # update source repo with updates from running get-sources-jenkins
+                    # update source repo with updates from running get-sources
                     cd ${WORKSPACE}/sources/''' + SYNC_REPOS[i] + '''
                     git add . -A -f
                     git commit -m "$COMMIT_MSG" || true
+                    git pull origin ''' + MIDSTM_BRANCH + ''' || true
                     git push origin ''' + MIDSTM_BRANCH + ''' || true
                   fi
                 ''')
@@ -123,7 +154,17 @@ timeout(180) {
                       [
                         $class: 'StringParameterValue',
                         name: 'UPDATE_BASE_IMAGES_FLAGS',
-                        value: UPDATE_BASE_IMAGES_FLAGS
+                        value: util.globalVar({UPDATE_BASE_IMAGES_FLAGS})
+                      ],
+                      [
+                        $class: 'StringParameterValue',
+                        name: 'nodeVersion',
+                        value: util.globalVar({nodeVersion})
+                      ],
+                      [
+                        $class: 'StringParameterValue',
+                        name: 'yarnVersion',
+                        value: util.globalVar({yarnVersion})
                       ],
                       [
                         $class: 'StringParameterValue',
