[jobs] Update from codeready-workspaces/crw-jenkins @ 76ad
Signed-off-by: Red Hat Devstudio Release Bot <nickboldt+devstudio-release@gmail.com>

diff --git a/crw-jenkins/jobs/CRW_CI/crw-machine-exec_2.x.jenkinsfile b/crw-jenkins/jobs/CRW_CI/crw-machine-exec_2.x.jenkinsfile
--- a/crw-jenkins/jobs/CRW_CI/crw-machine-exec_2.x.jenkinsfile
+++ b/crw-jenkins/jobs/CRW_CI/crw-machine-exec_2.x.jenkinsfile
@@ -7,14 +7,14 @@ import groovy.transform.Field
 // MIDSTM_BRANCH
 // FORCE_BUILD = "false"
 
-def SOURCE_REPO = "eclipse-che/che-machine-exec" // upstream source repo from which to find and sync commits to pkgs.devel repo
-def DWNSTM_REPO = "containers/codeready-workspaces-machineexec" // dist-git repo to use as target
+def SOURCE_REPO = "eclipse/che-machine-exec" // upstream source repo from which to find and sync commits to midstream repo
+def MIDSTM_REPO = "redhat-developer/codeready-workspaces-images" // repo to use as target
 def SYNC_REPO = "machineexec"
 def SYNC_FILES="activity api auth build cfg client cloud-shell common exec exec-info filter kubeconfig mocks output shell vendor ws-conn compile.sh CONTRIBUTING.md devfile.yaml go.mod go.sum LICENSE main.go VERSION README.md"
 
-def SOURCE_SHA=""
-def OLD_SHA=""
-def NEW_SHA=""
+def OLD_SOURCE_SHA=""
+def OLD_MID_SHA=""
+def NEW_MID_SHA=""
 
 def String nodeLabel = 'rhel8'
 timeout(120) {
@@ -32,40 +32,51 @@ timeout(120) {
         util.installSkopeoFromContainer("")
         util.installYq()
         util.bootstrap(CRW_KEYTAB)
-        util.cloneRepo("https://github.com/${SOURCE_REPO}.git", "${WORKSPACE}/sources", SOURCE_BRANCH)
-        util.cloneRepo("ssh://crw-build@pkgs.devel.redhat.com/${DWNSTM_REPO}", "${WORKSPACE}/targetdwn", MIDSTM_BRANCH)
 
-        SOURCE_SHA = util.getLastCommitSHA("${WORKSPACE}/sources")
+        println "########################################################################################################"
+        println "##  Clone and update github.com/${SOURCE_REPO}.git"
+        println "########################################################################################################"
+        SOURCE_DIR="${WORKSPACE}/sources"
+        util.cloneRepo("https://github.com/${SOURCE_REPO}.git", SOURCE_DIR, SOURCE_BRANCH)
+        OLD_SOURCE_SHA = util.getLastCommitSHA("${WORKSPACE}/sources")
+        println "Got OLD_SOURCE_SHA in sources folder: " + OLD_SOURCE_SHA
+        util.updateBaseImages(SOURCE_DIR, SOURCE_BRANCH, "-f Dockerfile --nocommit")        
 
-        OLD_SHA = util.getLastCommitSHA("${WORKSPACE}/targetdwn")
-        println "Got OLD_SHA in targetdwn folder: " + OLD_SHA
+        println "########################################################################################################"
+        println "##  Sync ${SYNC_REPO} to codeready-workspaces-images"
+        println "########################################################################################################"
+        util.cloneRepo("https://github.com/${MIDSTM_REPO}", "${WORKSPACE}/targetdwn", MIDSTM_BRANCH)
+        TARGET_DIR="${WORKSPACE}/targetdwn/" + util.getCRWLongName(SYNC_REPO)
+        OLD_MID_SHA = util.getLastCommitSHA("${WORKSPACE}/targetdwn")
+        println "Got OLD_SHA in targetdwn/${SYNC_REPO} folder: " + OLD_MID_SHA
 
-        util.updateBaseImages("${WORKSPACE}/sources", SOURCE_BRANCH, "-f Dockerfile --nocommit")
+        // rsync files to codeready-workspaces-images
+        sh('''#!/bin/bash -xe
+          SOURCEDIR="''' + SOURCE_DIR + '''"
+          TARGETDIR="''' + TARGET_DIR + '''"
+          SYNC_FILES="''' + SYNC_FILES + '''"
+          [ ! -d ${TARGETDIR} ] && mkdir -p ${TARGETDIR}
+          for d in ${SYNC_FILES}; do
+            if [[ -f ${SOURCEDIR}/${d} ]]; then
+              rsync -azrlt ${SOURCEDIR}/${d} ${TARGETDIR}/${d}
+            elif [[ -d ${SOURCEDIR}/${d} ]]; then
+              # copy over the dir contents
+              rsync -azrlt ${SOURCEDIR}/${d}/* ${TARGETDIR}/${d}/
+              # sync the directory and delete from targetdwn if deleted from source
+              rsync -azrlt --delete ${SOURCEDIR}/${d}/ ${TARGETDIR}/${d}/
+            fi
+          done
+        ''')
 
-        sh '''#!/bin/bash -xe
-hasChanged=0
-SOURCEDOCKERFILE=${WORKSPACE}/sources/build/dockerfiles/rhel.Dockerfile
-# rsync files in github to dist-git
-for d in ''' + SYNC_FILES + '''; do
-  if [[ -f ${WORKSPACE}/sources/${d} ]]; then
-    rsync -zrlt ${WORKSPACE}/sources/${d} ${WORKSPACE}/targetdwn/${d}
-  elif [[ -d ${WORKSPACE}/sources/${d} ]]; then
-    # copy over the files
-    rsync -zrlt ${WORKSPACE}/sources/${d}/* ${WORKSPACE}/targetdwn/${d}/
-    # sync the directory and delete from targetdwn if deleted from source
-    rsync -zrlt --delete ${WORKSPACE}/sources/${d}/ ${WORKSPACE}/targetdwn/${d}/
-  fi
-done
+        sh('''#!/bin/bash -xe
+          cp -f ''' + SOURCE_DIR + '''/build/dockerfiles/Dockerfile  ''' + TARGET_DIR + '''/Dockerfile
+          CRW_VERSION="''' + CRW_VERSION_F + '''"
+          #apply patches
+          sed -i ''' + TARGET_DIR + '''/Dockerfile \
+            -e "s#FROM registry.redhat.io/#FROM #g" \
+            -e "s#FROM registry.access.redhat.com/#FROM #g"
 
-cp -f ${SOURCEDOCKERFILE} ${WORKSPACE}/targetdwn/Dockerfile
-
-CRW_VERSION="''' + CRW_VERSION_F + '''"
-#apply patches
-sed -i ${WORKSPACE}/targetdwn/Dockerfile \
-  -e "s#FROM registry.redhat.io/#FROM #g" \
-  -e "s#FROM registry.access.redhat.com/#FROM #g"
-
-METADATA='ENV SUMMARY="Red Hat CodeReady Workspaces ''' + SYNC_REPO + ''' container" \\\r
+          METADATA='ENV SUMMARY="Red Hat CodeReady Workspaces ''' + SYNC_REPO + ''' container" \\\r
     DESCRIPTION="Red Hat CodeReady Workspaces ''' + SYNC_REPO + ''' container" \\\r
     PRODNAME="codeready-workspaces" \\\r
     COMPNAME="''' + SYNC_REPO + '''-rhel8" \r
@@ -82,49 +93,40 @@ LABEL summary="$SUMMARY" \\\r
       io.openshift.expose-services="" \\\r
       usage="" \r'
 
-echo -e "$METADATA" >> ${WORKSPACE}/targetdwn/Dockerfile
-'''
+          echo -e "$METADATA" >> ''' + TARGET_DIR + '''/Dockerfile
+        ''')
 
-        // push changes in github to dist-git
-        util.updateBaseImages("${WORKSPACE}/targetdwn", MIDSTM_BRANCH, "--nocommit")
-        sh '''#!/bin/bash -xe
-export KRB5CCNAME=/var/tmp/crw-build_ccache
-cd ${WORKSPACE}/targetdwn
-if [[ \$(git diff --name-only) ]]; then # file changed
-  git add Dockerfile ''' + SYNC_FILES + ''' . -A -f
-  # note this might fail if we're syncing from a tag vs. a branch
-  git commit -s -m "[sync] Update from ''' + SOURCE_REPO + ''' @ ''' + SOURCE_SHA + '''" Dockerfile ''' + SYNC_FILES + ''' . || true
-  git push origin ''' + MIDSTM_BRANCH + ''' || true
-  echo "[sync] Updated pkgs.devel @ \$(git rev-parse --short=4 HEAD) from ''' + SOURCE_REPO + ''' @ ''' + SOURCE_SHA + '''"
-fi
-cd ..
-'''
+        // push changes to codeready-workspaces-images
+        util.updateBaseImages(TARGET_DIR, MIDSTM_BRANCH, "--nocommit")
+        sh('''#!/bin/bash -xe
+          SYNC_FILES="''' + SYNC_FILES + '''"
+          cd ${WORKSPACE}/targetdwn
+          git add ''' + util.getCRWLongName(SYNC_REPO) + '''
+          git update-index --refresh  # ignore timestamp updates
+          if [[ \$(git diff-index HEAD --) ]]; then # file changed
+            cd ''' + TARGET_DIR + '''
+            git add Dockerfile ${SYNC_FILES} . -A -f
+            # note this might fail if we're syncing from a tag vs. a branch
+            git commit -s -m "[sync] Update from ''' + SOURCE_REPO + ''' @ ''' + OLD_SOURCE_SHA + '''" Dockerfile ${SYNC_FILES} . || true
+            git push origin ''' + MIDSTM_BRANCH + ''' || true
+            echo "[sync] Updated  @ \$(git rev-parse --short=4 HEAD) from ''' + SOURCE_REPO + ''' @ ''' + OLD_SOURCE_SHA + '''"
+          fi
+        ''')
         }
-        NEW_SHA = util.getLastCommitSHA("${WORKSPACE}/targetdwn")
-        println "Got NEW_SHA in targetdwn folder: " + NEW_SHA
+        NEW_MID_SHA = util.getLastCommitSHA("${WORKSPACE}/targetdwn")
+        println "Got NEW_MID_SHA in targetdwn folder: " + NEW_MID_SHA
 
-        if (NEW_SHA.equals(OLD_SHA) && !FORCE_BUILD.equals("true")) {
+        if (NEW_MID_SHA.equals(OLD_MID_SHA) && !FORCE_BUILD.equals("true")) {
           currentBuild.result='UNSTABLE'
         }
-      }
-    }
-  }
-}
 
-// kick off get-sources-rhpkg-container-build_2.y job
-node(nodeLabel){ 
-  stage ("Build container on ${nodeLabel}") {
-    println "########################################################################################################"
-    println "##  Build ${SYNC_REPO} containers"
-    println "########################################################################################################"
-    sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/'+ MIDSTM_BRANCH + '/product/util.groovy')
-    def util = load "${WORKSPACE}/util.groovy"
-    echo "currentBuild.result = " + currentBuild.result
-    if (!currentBuild.result.equals("ABORTED") && !currentBuild.result.equals("FAILURE")) {
-      if (!NEW_SHA.equals(OLD_SHA) || FORCE_BUILD.equals("true")) {
-        JOB_BRANCH = util.getJobBranch(MIDSTM_BRANCH)
-        build(
-              job: 'get-sources-rhpkg-container-build_' + JOB_BRANCH,
+        println "########################################################################################################"
+        println "##  Kickoff Sync to downstream job"
+        println "########################################################################################################"
+        if (!OLD_MID_SHA.equals(NEW_MID_SHA) || FORCE_BUILD == "true") {
+          JOB_BRANCH = util.getJobBranch(MIDSTM_BRANCH)
+          build(
+              job: 'crw-sync-to-downstream_' + JOB_BRANCH,
               wait: true,
               propagate: true,
               parameters: [
@@ -136,27 +138,22 @@ node(nodeLabel){
                 [
                   $class: 'StringParameterValue',
                   name: 'cause',
-                  value: "${SYNC_REPO}+respin+by+${BUILD_TAG}"
+                  value: SYNC_REPO + "+respin+by+${BUILD_TAG}"
                 ],
                 [
                   $class: 'StringParameterValue',
-                  name: 'GIT_BRANCH',
-                  value: "${MIDSTM_BRANCH}"
-                ],
-                [
-                  $class: 'StringParameterValue',
-                  name: 'GIT_PATHs',
-                  value: "${DWNSTM_REPO}"
-                ],
-                [
-                  $class: 'StringParameterValue',
-                  name: 'QUAY_REPO_PATHs',
-                  value: util.getCRWShortName(SYNC_REPO) + "-rhel8"
+                  name: 'REPOS',
+                  value: util.getCRWLongName(SYNC_REPO)
                 ],
                 [
                   $class: 'StringParameterValue',
                   name: 'JOB_BRANCH',
                   value: JOB_BRANCH
+                ],
+                [
+                  $class: 'StringParameterValue',
+                  name: 'MIDSTM_BRANCH',
+                  value: "${MIDSTM_BRANCH}"
                 ],
                 [
                   $class: 'BooleanParameterValue',
@@ -169,15 +166,14 @@ node(nodeLabel){
                   value: false
                 ]
               ]
-        )
-        currentBuild.description="Brew build triggered"
-      } else {
-        println "No changes upstream, nothing to build in brew!"
-        currentBuild.description="No Brew build"
-        currentBuild.result = 'UNSTABLE'
-      }
-    } else {
-      util.notifyBuildFailed()
-    } // if
-  } // stage
-} //node
+            )
+          currentBuild.description+="; Downstream sync job triggered"
+        } else {
+          println "No changes upstream, nothing to sync / build in brew!"
+          currentBuild.description+="; No sync or Brew build"
+          currentBuild.result = 'UNSTABLE'
+        }        
+      } // withCredentials
+    } // wrap
+  } // node
+} // timeout
diff --git a/crw-jenkins/jobs/CRW_CI/push-latest-container-to-quay_2.x.jenkinsfile b/crw-jenkins/jobs/CRW_CI/push-latest-container-to-quay_2.x.jenkinsfile
--- a/crw-jenkins/jobs/CRW_CI/push-latest-container-to-quay_2.x.jenkinsfile
+++ b/crw-jenkins/jobs/CRW_CI/push-latest-container-to-quay_2.x.jenkinsfile
@@ -201,6 +201,28 @@ pushd ${WORKSPACE}/sources/ >/dev/null
     git push origin ''' + MIDSTM_BRANCH + '''
 popd >/dev/null ''')
             }
+
+            sh (script: 'curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/'+MIDSTM_BRANCH+'/product/getLatestImageTags.sh && chmod +x getLatestImageTags.sh', returnStdout: true).trim().split( '\n' )
+            def NEW_OSBS_IMAGE = sh(script: '''./getLatestImageTags.sh --osbs -c codeready-workspaces-operator-metadata --tag ''' + CRW_VERSION.toString().replaceAll("\\.","\\\\.")), returnStdout: true).trim().split( '\n' )
+            println "####################################################################################################################"
+            println "##  Check registry-proxy.engineering.redhat.com/rh-osbs/iib for ${NEW_OSBS_IMAGE}"
+            println "####################################################################################################################"
+            def statusCode = sh(script: '''#!/bin/bash -xe
+# eg., registry-proxy.engineering.redhat.com/rh-osbs/codeready-workspaces-operator-metadata:2.7-30
+curl -sSLk "https://datagrepper.engineering.redhat.com/raw?topic=/topic/VirtualTopic.eng.ci.redhat-container-image.index.built&delta=1728000&rows_per_page=6&contains=codeready-workspaces" | jq ".raw_messages[].msg.index" > datagrepper.json
+FOUND=$(jq --arg NEW_OSBS_IMAGE "''' + NEW_OSBS_IMAGE + '''" '. | select(.added_bundle_images[] == $NEW_OSBS_IMAGE)' 2>/dev/null datagrepper.json)
+if [[ $FOUND ]]; then
+  echo $FOUND
+  rm -f datagrepper.json
+else
+  echo "[ERROR] Could not find ''' + NEW_OSBS_IMAGE + ''' in https://datagrepper.engineering.redhat.com/raw?topic=/topic/VirtualTopic.eng.ci.redhat-container-image.index.built&delta=1728000&rows_per_page=6&contains=codeready-workspaces (when piped to jq '.raw_messages[].msg.index')
+  exit 1
+fi
+''', returnStatus:true)
+            if (statusCode > 0) {
+                currentBuild.result = 'FAILURE'
+                currentBuild.description=currentBuild.description+"; ERROR: rh-osbs/iib NOT updated!"
+            }
         } else {
             println "No changes to LATEST_IMAGES; no need to trigger update-digests-in-registries-and-metadata_" + CRW_VERSION
             currentBuild.result = 'UNSTABLE'
