[jobs] Update from codeready-workspaces/crw-jenkins @ 0f1b
Signed-off-by: Red Hat Devstudio Release Bot <nickboldt+devstudio-release@gmail.com>

diff --git a/crw-jenkins/jobs/CRW_CI/crw-jwtproxy_2.x.jenkinsfile b/crw-jenkins/jobs/CRW_CI/crw-jwtproxy_2.x.jenkinsfile
--- a/crw-jenkins/jobs/CRW_CI/crw-jwtproxy_2.x.jenkinsfile
+++ b/crw-jenkins/jobs/CRW_CI/crw-jwtproxy_2.x.jenkinsfile
@@ -8,9 +8,8 @@ import groovy.transform.Field
 // MIDSTM_BRANCH 
 
 def SOURCE_REPO = "eclipse/che-jwtproxy" // upstream source repo from which to find and sync commits
-def DWNSTM_REPO = "redhat-developer/codeready-workspaces-images" // repo to use as target
-
-def SYNC_REPO = "jwtproxy" // also used for the Brew dockerfile params
+def MIDSTM_REPO = "redhat-developer/codeready-workspaces-images" // repo to use as target
+def SYNC_REPO = "jwtproxy"
 def SYNC_FILES="cmd config examples jwt proxy stop go.mod go.sum jwtproxy.go LICENSE README.md vendor"
 
 def OLD_SHA=""
@@ -26,63 +25,64 @@ timeout(120) {
         cleanWs()
         CRW_VERSION = util.getCrwVersion(MIDSTM_BRANCH)
         println "CRW_VERSION = '" + CRW_VERSION + "'"
+        withCredentials([string(credentialsId:'crw_devstudio-release-token', variable: 'GITHUB_TOKEN'), 
+            usernamePassword(credentialsId: 'registry.redhat.io_crw_bot', usernameVariable: 'CRW_BOT_USERNAME', passwordVariable: 'CRW_BOT_PASSWORD'),
+            file(credentialsId: 'crw_crw-build-keytab', variable: 'CRW_KEYTAB')]) {
         util.installSkopeoFromContainer("")
         util.installYq()
-        withCredentials([string(credentialsId:'crw_devstudio-release-token', variable: 'GITHUB_TOKEN'), 
-            file(credentialsId: 'crw_crw-build-keytab', variable: 'CRW_KEYTAB')]) {
-          util.bootstrap(CRW_KEYTAB)
+        util.bootstrap(CRW_KEYTAB)
 
-          println "########################################################################################################"
-          println "##  Clone and update github.com/${SOURCE_REPO}.git"
-          println "########################################################################################################"
-          SOURCE_DIR="${WORKSPACE}/sources"
-          util.cloneRepo("https://github.com/${SOURCE_REPO}.git", SOURCE_DIR, SOURCE_BRANCH)
-          SOURCE_SHA = util.getLastCommitSHA(SOURCE_DIR)
+        println "########################################################################################################"
+        println "##  Clone and update github.com/${SOURCE_REPO}.git"
+        println "########################################################################################################"
+        SOURCE_DIR="${WORKSPACE}/sources"
+        util.cloneRepo("https://github.com/${SOURCE_REPO}.git", SOURCE_DIR, SOURCE_BRANCH)
+        SOURCE_SHA = util.getLastCommitSHA(SOURCE_DIR)
 
-          // can't yet generate a PR against eclipse/che-* repos, and can't push directly
-          // so check for a new base image but DO NOT commit/push/pull-request
-          util.updateBaseImages(SOURCE_DIR, MIDSTM_BRANCH, "-f rhel.Dockerfile --nocommit")
+        // can't yet generate a PR against eclipse/che-* repos, and can't push directly
+        // so check for a new base image but DO NOT commit/push/pull-request
+        util.updateBaseImages(SOURCE_DIR, SOURCE_BRANCH, "-f rhel.Dockerfile --nocommit")
 
-          println "########################################################################################################"
-          println "##  Sync ${SYNC_REPO} to codeready-workspaces-images"
-          println "########################################################################################################"
-          util.cloneRepo("https://github.com/${DWNSTM_REPO}", "${WORKSPACE}/targetdwn", MIDSTM_BRANCH)
-          TARGET_DIR="${WORKSPACE}/targetdwn/" + util.getCRWLongName(SYNC_REPO)
-          OLD_SHA = util.getLastCommitSHA("${WORKSPACE}/targetdwn")
-          println "Got OLD_SHA in targetdwn folder: " + OLD_SHA
+        println "########################################################################################################"
+        println "##  Sync ${SYNC_REPO} to codeready-workspaces-images"
+        println "########################################################################################################"
+        util.cloneRepo("https://github.com/${MIDSTM_REPO}", "${WORKSPACE}/targetdwn", MIDSTM_BRANCH)
+        TARGET_DIR="${WORKSPACE}/targetdwn/" + util.getCRWLongName(SYNC_REPO)
+        OLD_SHA = util.getLastCommitSHA("${WORKSPACE}/targetdwn")
+        println "Got OLD_SHA in targetdwn folder: " + OLD_SHA
 
-          // rsync files to codeready-workspaces-images
-          sh('''#!/bin/bash -xe
-            SOURCEDIR="''' + SOURCE_DIR + '''"
-            TARGETDIR="''' + TARGET_DIR + '''"
-            SYNC_FILES="''' + SYNC_FILES + '''"
-            [ ! -d ${TARGETDIR} ] && mkdir -p ${TARGETDIR}
-            for d in ${SYNC_FILES}; do
-              if [[ -f ${SOURCEDIR}/${d} ]]; then
-                rsync -azrlt ${SOURCEDIR}/${d} ${TARGETDIR}/${d}
-              elif [[ -d ${SOURCEDIR}/${d} ]]; then
-                # copy over the dir contents
-                rsync -azrlt ${SOURCEDIR}/${d}/* ${TARGETDIR}/${d}/
-                # sync the directory and delete from targetdwn if deleted from source
-                rsync -azrlt --delete ${SOURCEDIR}/${d}/ ${TARGETDIR}/${d}/
-              fi
-            done
-          ''')
+        // rsync files to codeready-workspaces-images
+        sh('''#!/bin/bash -xe
+          SOURCEDIR="''' + SOURCE_DIR + '''"
+          TARGETDIR="''' + TARGET_DIR + '''"
+          SYNC_FILES="''' + SYNC_FILES + '''"
+          [ ! -d ${TARGETDIR} ] && mkdir -p ${TARGETDIR}
+          for d in ${SYNC_FILES}; do
+            if [[ -f ${SOURCEDIR}/${d} ]]; then
+              rsync -azrlt ${SOURCEDIR}/${d} ${TARGETDIR}/${d}
+            elif [[ -d ${SOURCEDIR}/${d} ]]; then
+              # copy over the dir contents
+              rsync -azrlt ${SOURCEDIR}/${d}/* ${TARGETDIR}/${d}/
+              # sync the directory and delete from targetdwn if deleted from source
+              rsync -azrlt --delete ${SOURCEDIR}/${d}/ ${TARGETDIR}/${d}/
+            fi
+          done
+        ''')
 
-          sh('''#!/bin/bash -xe
-            cp -f ''' + SOURCE_DIR + '''/build/dockerfiles/rhel.Dockerfile ''' + TARGET_DIR + '''/Dockerfile
-            CRW_VERSION="''' + CRW_VERSION_F + '''"
-            #apply patches
-            sed -i ''' + TARGET_DIR + '''/Dockerfile \
-              -e "s@^FROM \\(registry.access.redhat.com/devtools/.\\+\\)@# FROM \\1@g" \
-              -e "s@# *FROM registry.redhat.io/\\(rhel8.\\+\\)@FROM \\1@g" \
-              -e "s@FROM registry.access.redhat.com/\\(ubi8-minimal\\)@FROM \\1@g" \
-              `# Replace go-toolset rhel7 with rhel8 version` \
-              -e "s#devtools/go-toolset-rhel7#rhel8/go-toolset#g" \
-              -e "s#ENV PATH=/opt/rh/go-toolset.+PATH ##g" \
-              -e "s@ENV PATH=@# ENV PATH=@g"
+        sh('''#!/bin/bash -xe
+          cp -f ''' + SOURCE_DIR + '''/build/dockerfiles/rhel.Dockerfile ''' + TARGET_DIR + '''/Dockerfile
+          CRW_VERSION="''' + CRW_VERSION_F + '''"
+          #apply patches
+          sed -i ''' + TARGET_DIR + '''/Dockerfile \
+            -e "s@^FROM \\(registry.access.redhat.com/devtools/.\\+\\)@# FROM \\1@g" \
+            -e "s@# *FROM registry.redhat.io/\\(rhel8.\\+\\)@FROM \\1@g" \
+            -e "s@FROM registry.access.redhat.com/\\(ubi8-minimal\\)@FROM \\1@g" \
+            `# Replace go-toolset rhel7 with rhel8 version` \
+            -e "s#devtools/go-toolset-rhel7#rhel8/go-toolset#g" \
+            -e "s#ENV PATH=/opt/rh/go-toolset.+PATH ##g" \
+            -e "s@ENV PATH=@# ENV PATH=@g"
 
-            METADATA='ENV SUMMARY="Red Hat CodeReady Workspaces ''' + SYNC_REPO + ''' container" \\\r
+          METADATA='ENV SUMMARY="Red Hat CodeReady Workspaces ''' + SYNC_REPO + ''' container" \\\r
 DESCRIPTION="Red Hat CodeReady Workspaces ''' + SYNC_REPO + ''' container" \\\r
 PRODNAME="codeready-workspaces" \\\r
 COMPNAME="''' + SYNC_REPO + '''-rhel8" \r
@@ -99,55 +99,41 @@ maintainer="Nick Boldt <nboldt@redhat.com>" \\\r
 io.openshift.expose-services="" \\\r
 usage="" \r'
 
-            echo -e "$METADATA" >> ''' + TARGET_DIR + '''/Dockerfile
-          ''')
+          echo -e "$METADATA" >> ''' + TARGET_DIR + '''/Dockerfile
+        ''')
 
-          // push changes in github to codeready-workspaces-images
-          util.updateBaseImages(TARGET_DIR, MIDSTM_BRANCH, "--nocommit")
-          sh('''#!/bin/bash -xe
-            export KRB5CCNAME=/var/tmp/crw-build_ccache
-            SYNC_FILES="''' + SYNC_FILES + '''"
-            cd ${WORKSPACE}/targetdwn
-            git add ''' + util.getCRWLongName(SYNC_REPO) + '''
-            git update-index --refresh || true # ignore timestamp updates
-            if [[ \$(git diff-index HEAD --) ]]; then # file changed
-              cd ''' + TARGET_DIR + '''
-              git add Dockerfile ${SYNC_FILES}
-              # note this might fail if we're syncing from a tag vs. a branch
-              git commit -s -m "[sync] Update from ''' + SOURCE_REPO + ''' @ ''' + SOURCE_SHA + '''" Dockerfile ${SYNC_FILES}
-              git push origin ''' + MIDSTM_BRANCH + ''' || true
-              NEW_SHA=\$(git rev-parse --short=4 HEAD) # echo ${NEW_SHA}
-              echo "[sync] Updated codeready-workspaces-images @ ${NEW_SHA} from ''' + SOURCE_REPO + ''' @ ''' + SOURCE_SHA + '''"
-            fi
-          ''')
-          NEW_SHA = util.getLastCommitSHA("${WORKSPACE}/targetdwn")
-          println "Got NEW_SHA in targetdwn folder: " + NEW_SHA
-          currentBuild.description="Upstream sync done"
+        // push changes to codeready-workspaces-images
+        util.updateBaseImages(TARGET_DIR, MIDSTM_BRANCH, "--nocommit")
+        sh('''#!/bin/bash -xe
+          SYNC_FILES="''' + SYNC_FILES + '''"
+          cd ${WORKSPACE}/targetdwn
+          git add ''' + util.getCRWLongName(SYNC_REPO) + '''
+          git update-index --refresh || true # ignore timestamp updates
+          if [[ \$(git diff-index HEAD --) ]]; then # file changed
+            cd ''' + TARGET_DIR + '''
+            git add Dockerfile ${SYNC_FILES} . -A -f
+            # note this might fail if we're syncing from a tag vs. a branch
+            git commit -s -m "[sync] Update from ''' + SOURCE_REPO + ''' @ ''' + SOURCE_SHA + '''" Dockerfile ${SYNC_FILES} . || true
+            git push origin ''' + MIDSTM_BRANCH + ''' || true
+            NEW_SHA=\$(git rev-parse --short=4 HEAD) # echo ${NEW_SHA}
+            echo "[sync] Updated codeready-workspaces-images @ ${NEW_SHA} from ''' + SOURCE_REPO + ''' @ ''' + SOURCE_SHA + '''"
+          fi
+        ''')
+        }
+        NEW_SHA = util.getLastCommitSHA("${WORKSPACE}/targetdwn")
+        println "Got NEW_SHA in targetdwn folder: " + NEW_SHA
 
-          if (NEW_SHA.equals(OLD_SHA) && !FORCE_BUILD.equals("true")) {
-            currentBuild.result='UNSTABLE'
-          }
-        } //withCredentials
-      } // wrap
-    } // stage
-  } // node
-} // timeout
+        if (NEW_SHA.equals(OLD_SHA) && !FORCE_BUILD.equals("true")) {
+          currentBuild.result='UNSTABLE'
+        }
+        currentBuild.description="Upstream sync done"
 
-// kick off get-sources-rhpkg-container-build_2.y job
-node(nodeLabel) {
-  stage ("Build container on ${nodeLabel}") {
-    println "########################################################################################################"
-    println "##  Build ${SYNC_REPO} container"
-    println "########################################################################################################"
-    sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/'+ MIDSTM_BRANCH + '/product/util.groovy')
-    def util = load "${WORKSPACE}/util.groovy"
-    echo "currentBuild.result = " + currentBuild.result
-    if (!currentBuild.result.equals("ABORTED") && !currentBuild.result.equals("FAILURE")) {
-      if (NEW_SHA != OLD_SHA || FORCE_BUILD == "true") {
-        CRW_VERSION = util.getCrwVersion(MIDSTM_BRANCH)
-        println "CRW_VERSION = '" + CRW_VERSION + "'"
-        JOB_BRANCH = util.getJobBranch(MIDSTM_BRANCH)
-        build(
+        println "########################################################################################################"
+        println "##  Kickoff Sync to downstream job"
+        println "########################################################################################################"
+        if (!OLD_SHA.equals(NEW_SHA) || FORCE_BUILD == "true") {
+          JOB_BRANCH = util.getJobBranch(MIDSTM_BRANCH)
+          build(
               job: 'crw-sync-to-downstream_' + JOB_BRANCH,
               wait: true,
               propagate: true,
@@ -160,7 +146,7 @@ node(nodeLabel) {
                 [
                   $class: 'StringParameterValue',
                   name: 'cause',
-                  value: "${SYNC_REPO}+respin+by+${BUILD_TAG}"
+                  value: SYNC_REPO + "+respin+by+${BUILD_TAG}"
                 ],
                 [
                   $class: 'StringParameterValue',
@@ -188,15 +174,14 @@ node(nodeLabel) {
                   value: false
                 ]
               ]
-        )
-        currentBuild.description+="; Downstream sync job triggered"
-      } else {
-        println "No changes upstream, nothing to sync / build in brew!"
-        currentBuild.description+="; No sync or Brew build"
-        currentBuild.result = 'UNSTABLE'
-      }
-    } else {
-      util.notifyBuildFailed()
-    } // if
-  } // stage
-} //node
+            )
+          currentBuild.description+="; Downstream sync job triggered"
+        } else {
+          println "No changes upstream, nothing to sync / build in brew!"
+          currentBuild.description+="; No sync or Brew build"
+          currentBuild.result = 'UNSTABLE'
+        }        
+      } // withCredentials
+    } // wrap
+  } // node
+} // timeout
