[jobs] Update from codeready-workspaces/crw-jenkins @ 1b707
Signed-off-by: Red Hat Devstudio Release Bot <nickboldt+devstudio-release@gmail.com>

diff --git a/crw-jenkins/jobs/CRW_CI/crw-pluginregistry_2.x.jenkinsfile b/crw-jenkins/jobs/CRW_CI/crw-pluginregistry_2.x.jenkinsfile
--- a/crw-jenkins/jobs/CRW_CI/crw-pluginregistry_2.x.jenkinsfile
+++ b/crw-jenkins/jobs/CRW_CI/crw-pluginregistry_2.x.jenkinsfile
@@ -2,6 +2,8 @@
 
 import groovy.transform.Field
 
+// DEPRECATED! See template_2.x.jenkinsfile for replacement
+
 // PARAMETERS for this pipeline:
 // def FORCE_BUILD = "false"
 // MIDSTM_BRANCH
@@ -13,14 +15,13 @@ def DWNSTM_REPO = "redhat-developer/codeready-workspaces-images" // dist-git rep
 def DWNSTM_BRANCH = MIDSTM_BRANCH // target branch in dist-git repo, eg., crw-2.y-rhel-8
 def SYNC_REPO = "pluginregistry" // also used for the Brew dockerfile params
 def USE_DIGESTS = "true" // if true, use @sha256:digest in registry; if false, use :tag
-def SYNC_FILES="build deploy openshift v3 .gitignore .htaccess LICENSE README.md VERSION"
 
 def OLD_SHA_MID=""
 def OLD_SHA_DWN=""
 def NEW_SHA_MID=""
 def NEW_SHA_DWN=""
 
-def buildNode = "rhel8" // node label
+def buildNode = "rhel8||s390x-rhel8||ppc64le-rhel8" // node label(s)
 timeout(120) {
   node("${buildNode}"){ stage "Sync repos"
     wrap([$class: 'TimestamperBuildWrapper']) {
@@ -42,12 +43,6 @@ timeout(120) {
         println "Got OLD_SHA_MID in targetmid folder: " + OLD_SHA_MID
         SOURCE_DIR="${WORKSPACE}/targetmid/dependencies/che-plugin-registry/"
 
-        // Check if che-machine-exec and che-theia plugins are current in upstream repo and if not, add them
-        sh('''#!/bin/bash -xe
-          cd ''' + SOURCE_DIR + '''
-          ./build/scripts/add_che_plugins.sh -b ''' + MIDSTM_BRANCH + ''' $(cat ${WORKSPACE}/targetmid/pom.xml | grep -E "<che.version>" | sed -r -e "s#.+<che.version>(.+)</che.version>#\\1#")
-        ''')
-
         util.updateBaseImages(SOURCE_DIR + "build/dockerfiles", DWNSTM_BRANCH)
         NEW_SHA_MID = util.getLastCommitSHA("${WORKSPACE}/targetmid")
         println "Got NEW_SHA_MID in targetmid folder: " + NEW_SHA_MID
@@ -62,21 +57,17 @@ timeout(120) {
 
         // rsync files to codeready-workspaces-images
         sh('''#!/bin/bash -xe
-          SOURCEDIR="''' + SOURCE_DIR + '''"
-          TARGETDIR="''' + TARGET_DIR + '''"
-          SYNC_FILES="''' + SYNC_FILES + '''"
-          [ ! -d ${TARGETDIR} ] && mkdir -p ${TARGETDIR}
-          for d in ${SYNC_FILES}; do
-            if [[ -f ${SOURCEDIR}/${d} ]]; then
-              rsync -azrlt ${SOURCEDIR}/${d} ${TARGETDIR}/${d}
-            elif [[ -d ${SOURCEDIR}/${d} ]]; then
-              # copy over the dir contents
-              rsync -azrlt ${SOURCEDIR}/${d}/* ${TARGETDIR}/${d}/
-              # sync the directory and delete from targetdwn if deleted from source
-              rsync -azrlt --delete ${SOURCEDIR}/${d}/ ${TARGETDIR}/${d}/
-            else
-              echo "[WARN] Could not find ${SOURCEDIR}/${d} to sync to ${TARGETDIR}/${d}"
-            fi
+SOURCEDIR="''' + SOURCE_DIR + '''"
+TARGETDIR="''' + TARGET_DIR + '''"
+[ ! -d ${TARGETDIR} ] && mkdir -p ${TARGETDIR}
+rsync -azrlt --delete ${SOURCEDIR} ${TARGETDIR}
+        ''')
+
+        // CRW-1792 transform che-editors.yaml#L5 and che-plugins.yaml#L3 to refer to /latest
+        sh('''#!/bin/bash -xe
+          cd ''' + TARGET_DIR + '''
+          for d in che-editors.yaml che-plugins.yaml; do 
+            sed -i ${d} -r -e "s|/nightly|/latest|" -e "s|/next|/latest|"
           done
         ''')
 
@@ -136,18 +127,17 @@ LABEL summary="$SUMMARY" \\\r
         // push changes to codeready-workspaces-images
         util.updateBaseImages(TARGET_DIR, DWNSTM_BRANCH, "--nocommit")
         sh('''#!/bin/bash -xe
-          SYNC_FILES="''' + SYNC_FILES + '''"
-          cd ${WORKSPACE}/targetdwn
-          git add ''' + util.getCRWLongName(SYNC_REPO) + '''
-          git update-index --refresh || true # ignore timestamp updates
-          if [[ \$(git diff-index HEAD --) ]]; then # file changed
-            cd ''' + TARGET_DIR + '''
-            git add Dockerfile ${SYNC_FILES} . -A -f
-            # note this might fail if we're syncing from a tag vs. a branch
-            git commit -s -m "[sync] Update from ''' + MIDSTM_REPO + ''' @ ''' + NEW_SHA_MID + '''" Dockerfile ${SYNC_FILES} . || true
-            git push origin ''' + DWNSTM_BRANCH + ''' || true
-            echo "[sync] Updated pkgs.devel @ \$(git rev-parse --short=4 HEAD) from ''' + MIDSTM_REPO + ''' @ ''' + NEW_SHA_MID + '''"
-          fi
+cd ${WORKSPACE}/targetdwn
+git add ''' + util.getCRWLongName(SYNC_REPO) + '''
+git update-index --refresh || true # ignore timestamp updates
+if [[ \$(git diff-index HEAD --) ]]; then # file changed
+  cd ''' + TARGET_DIR + '''
+  git add Dockerfile . -A -f
+  # note this might fail if we're syncing from a tag vs. a branch
+  git commit -s -m "[sync] Update from ''' + MIDSTM_REPO + ''' @ ''' + NEW_SHA_MID + '''" Dockerfile . || true
+  git push origin ''' + DWNSTM_BRANCH + ''' || true
+  echo "[sync] Updated pkgs.devel @ \$(git rev-parse --short=4 HEAD) from ''' + MIDSTM_REPO + ''' @ ''' + NEW_SHA_MID + '''"
+fi
         ''')
 
         NEW_SHA_DWN = util.getLastCommitSHA("${WORKSPACE}/targetdwn")
