[jobs] Update from codeready-workspaces/crw-jenkins @ f667
Signed-off-by: Red Hat Devstudio Release Bot <nickboldt+devstudio-release@gmail.com>

diff --git a/crw-jenkins/jobs/CRW_CI/crw-operator-metadata_2.9.jenkinsfile b/crw-jenkins/jobs/CRW_CI/crw-operator-metadata_2.9.jenkinsfile
--- a/crw-jenkins/jobs/CRW_CI/crw-operator-metadata_2.9.jenkinsfile
+++ b/crw-jenkins/jobs/CRW_CI/crw-operator-metadata_2.9.jenkinsfile
@@ -5,16 +5,15 @@ import groovy.transform.Field
 // PARAMETERS for this pipeline:
 // SOURCE_BRANCH
 // MIDSTM_BRANCH
-// JOB_BRANCH
 // CSV_VERSION
 // CSV_VERSION_PREV
-// FORCE_BUILD = "false"
+// FORCE_BUILD
 
-def SOURCE_REPO = "eclipse/che-operator" //source repo from which to find and sync commits to pkgs.devel repo
+def SOURCE_REPO = "eclipse-che/che-operator" //source repo from which to find and sync commits to pkgs.devel repo
 def MIDSTM_REPO = "redhat-developer/codeready-workspaces-operator" //source repo from which to find and sync commits to pkgs.devel repo
-def DWNSTM_REPO = "containers/codeready-workspaces-operator-metadata" // dist-git repo to use as target
-def SCRATCH = "false"
+def DWNSTM_REPO = "redhat-developer/codeready-workspaces-images" // downstream repo (before pkgs.devel)
 def SYNC_REPO = "operator-metadata" // also used for the Brew dockerfile params
+def OLM_CHANNEL = "nightly" // use nightly: stable channel has generated relatedImages section, which conflicts with Brew's digest pinning
 
 def SOURCE_SHA=""
 def OLD_SHA_MID=""
@@ -22,7 +21,7 @@ def OLD_SHA_DWN=""
 def NEW_SHA_MID=""
 def NEW_SHA_DWN=""
 
-def String nodeLabel = 'rhel8'
+def String nodeLabel = 'rhel8||s390x-rhel8||ppc64le-rhel8'
 timeout(120) {
   node(nodeLabel) {
     stage ("Sync repos on ${nodeLabel}") {
@@ -36,14 +35,14 @@ timeout(120) {
           util.installYq()
           println "CSV_VERSION = '" + CSV_VERSION + "'"
           // need to call this to set CRW_BRANCH_F for util.updateBaseImages
-          CRW_VERSION = JOB_BRANCH
+          CRW_VERSION = util.getCrwVersion(MIDSTM_BRANCH)
           println "CRW_VERSION = '" + CRW_VERSION + "'"
-          QUAY_REPO_PATH=util.getCRWShortName(SYNC_REPO) + "-rhel8"
-          util.bootstrap(CRW_KEYTAB)
 
-          util.cloneRepo("https://github.com/${SOURCE_REPO}.git", "${WORKSPACE}/sources", SOURCE_BRANCH)
-          util.cloneRepo("https://github.com/${MIDSTM_REPO}.git", "${WORKSPACE}/targetmid", MIDSTM_BRANCH)
-          util.cloneRepo("ssh://crw-build@pkgs.devel.redhat.com/${DWNSTM_REPO}", "${WORKSPACE}/targetdwn", MIDSTM_BRANCH)
+          QUAY_REPO_PATH=util.getCRWShortName(SYNC_REPO) + "-rhel8"
+
+          util.cloneRepoWithBootstrap("https://github.com/${SOURCE_REPO}.git", "${WORKSPACE}/sources", SOURCE_BRANCH, true)
+          util.cloneRepoWithBootstrap("https://github.com/${MIDSTM_REPO}.git", "${WORKSPACE}/targetmid", MIDSTM_BRANCH, true)
+          util.cloneRepoWithBootstrap("https://github.com/${DWNSTM_REPO}.git", "${WORKSPACE}/targetdwn", MIDSTM_BRANCH, false)
 
           // UP2MID are right now ONLY files in olm/ folder upstream copied to build/scripts/ folder midstream
           // TODO add in addDigests.sh buildDigestMap.sh from upstream (which are very different from downsteam versions)
@@ -55,31 +54,37 @@ timeout(120) {
           OLD_SHA_MID = util.getLastCommitSHA("${WORKSPACE}/targetmid")
           println "Got OLD_SHA_MID in targetmid folder: " + OLD_SHA_MID
 
-          OLD_SHA_DWN = util.getLastCommitSHA("${WORKSPACE}/targetdwn")
+          TARGET_DIR="${WORKSPACE}/targetdwn/" + util.getCRWLongName(SYNC_REPO) + "/"
+          OLD_SHA_DWN = util.getLastCommitSHA("${TARGET_DIR}")
           println "Got OLD_SHA_DWN in targetdwn folder: " + OLD_SHA_DWN
 
           def SOURCEDOCKERFILE="${WORKSPACE}/targetmid/operator-metadata.Dockerfile"
           sh '''
-# rsync files in upstream github to dist-git
+# rsync files in upstream github to crw-images repo
+SOURCEDIR="${WORKSPACE}/sources"
+TARGET_DIR="''' + TARGET_DIR + '''"
+[ ! -d ${TARGET_DIR} ] && mkdir -p ${TARGET_DIR}
 for d in ''' + SYNC_FILES_UP2MID + '''; do
-  if [[ -f ${WORKSPACE}/sources/olm/${d} ]]; then
-    rsync -zrlt ${WORKSPACE}/sources/olm/${d} ${WORKSPACE}/targetmid/build/scripts/${d}
-  elif [[ -d ${WORKSPACE}/sources/olm/${d} ]]; then
-    # copy over the files
-    rsync -zrlt ${WORKSPACE}/sources/olm/${d}/* ${WORKSPACE}/targetmid/build/scripts/${d}/
-    # sync the directory and delete from targetmid if deleted from source
-    rsync -zrlt --delete ${WORKSPACE}/sources/olm/${d}/ ${WORKSPACE}/targetmid/build/scripts/${d}/
+  if [[ -f ${SOURCEDIR}/olm/${d} ]]; then
+    rsync -azrlt ${SOURCEDIR}/olm/${d} ${TARGET_DIR}/build/scripts/${d}
+  elif [[ -d ${SOURCEDIR}/olm/${d} ]]; then
+    # copy over the dir contents
+    rsync -azrlt ${SOURCEDIR}/olm/${d}/* ${TARGET_DIR}/build/scripts/${d}/
+    # sync the directory and delete if deleted from source
+    rsync -azrlt --delete ${SOURCEDIR}/olm/${d}/ ${TARGET_DIR}/build/scripts/${d}/
+  else
+   echo "[WARN] Could not find ${SOURCEDIR}/${d} to sync to ${TARGET_DIR}/${d}"
   fi
 done
 
 CSV_NAME="codeready-workspaces"
-CSV_FILE="\$( { find ${WORKSPACE}/targetdwn/manifests/ -name "${CSV_NAME}.csv.yaml" | tail -1; } || true)"; 
+CSV_FILE="\$( { find ${TARGET_DIR}/manifests/ -name "${CSV_NAME}.csv.yaml" | tail -1; } || true)"; 
 echo "[INFO] CSV_FILE = ${CSV_FILE}"
 # if [[ ! ${CSV_FILE} ]]; then 
   # CRW-878 generate CSV and update CRD from upstream
   cd ${WORKSPACE}/targetmid/build/scripts
   ./sync-che-olm-to-crw-olm.sh -v ''' + CSV_VERSION + ''' -p ''' + CSV_VERSION_PREV + ''' \
-    -s ${WORKSPACE}/sources -t ${WORKSPACE}/targetmid --crw-branch ''' + MIDSTM_BRANCH
+    -s ${WORKSPACE}/sources -t ${WORKSPACE}/targetmid --olm-channel ''' + OLM_CHANNEL + ''' --crw-branch ''' + MIDSTM_BRANCH
 
           util.updateBaseImages("${WORKSPACE}/targetmid", MIDSTM_BRANCH, 
             "-f " + SOURCEDOCKERFILE.replaceAll(/^.+\//,"") + " -maxdepth 1 --nocommit")
@@ -87,13 +92,13 @@ echo "[INFO] CSV_FILE = ${CSV_FILE}"
           sh '''
   cd ${WORKSPACE}/targetmid/
   # if anything has changed other than the createdAt date, then we commit this
-  if [[ $(git diff | grep -v createdAt | egrep "^(-|\\+) ") ]]; then
-    git add . -A -f
-    git commit -s -m "[csv] Add CSV ''' + CSV_VERSION + '''" .
+  if [[ $(git diff | grep -v createdAt | egrep "^(-|\\+) " || true) ]]; then
+    git add . -A -f || true
+    git commit -s -m "[csv] Add CSV ''' + CSV_VERSION + '''" . || true
     git push origin ''' + MIDSTM_BRANCH + '''
   else # no need to push this so revert
     echo "[INFO] No significant changes (other than createdAt date) so revert and do not commit"
-    git checkout manifests/ build/scripts/
+    git checkout manifests/ build/scripts/ || true
   fi
 # fi
 '''
@@ -103,31 +108,31 @@ echo "[INFO] CSV_FILE = ${CSV_FILE}"
           def SYNC_FILES_MID2DWN = "manifests metadata build" // folders in mid/dwn
 
           sh '''
-# rsync files in github midstream to dist-git downstream
+TARGET_DIR="''' + TARGET_DIR + '''"
+# rsync files in midstream github to dist-git
 for d in ''' + SYNC_FILES_MID2DWN + '''; do
   if [[ -f ${WORKSPACE}/targetmid/${d} ]]; then
-    rsync -zrlt ${WORKSPACE}/targetmid/${d} ${WORKSPACE}/targetdwn/${d}
+    rsync -azrlt ${WORKSPACE}/targetmid/${d} ${TARGET_DIR}/${d}
   elif [[ -d ${WORKSPACE}/targetmid/${d} ]]; then
     # copy over the files
-    rsync -zrlt ${WORKSPACE}/targetmid/${d}/* ${WORKSPACE}/targetdwn/${d}/
-    # sync the directory and delete from targetdwn if deleted from targetmid
-    rsync -zrlt --delete ${WORKSPACE}/targetmid/${d}/ ${WORKSPACE}/targetdwn/${d}/
+    rsync -azrlt ${WORKSPACE}/targetmid/${d}/* ${TARGET_DIR}/${d}/
+    # sync the directory and delete if deleted from source
+    rsync -azrlt --delete ${WORKSPACE}/targetmid/${d}/ ${TARGET_DIR}/${d}/
   fi
 done
 
-cp -f ''' + SOURCEDOCKERFILE + ''' ${WORKSPACE}/targetdwn/Dockerfile
+cp -f ''' + SOURCEDOCKERFILE + ''' ${TARGET_DIR}/Dockerfile
 
-CRW_VERSION="''' + CRW_VERSION + '''"
-#apply patches
-sed -i ${WORKSPACE}/targetdwn/Dockerfile \
+# apply standard patches to convert from midstream public to downstream Brew build
+sed -i ${TARGET_DIR}/Dockerfile \
   -e "s#FROM registry.redhat.io/#FROM #g" \
   -e "s#FROM registry.access.redhat.com/#FROM #g" \
-  -e "s/# *RUN yum /RUN yum /g" \
+  -e "s/# *RUN yum /RUN yum /g"
 
 # generate digests from tags
 # 1. convert csv to use brew container refs so we can resolve stuff
 CSV_NAME="codeready-workspaces"
-CSV_FILE="\$(find ${WORKSPACE}/targetdwn/manifests/ -name "${CSV_NAME}.csv.yaml" | tail -1)"; # echo "[INFO] CSV = ${CSV_FILE}"
+CSV_FILE="\$(find ${TARGET_DIR}/manifests/ -name "${CSV_NAME}.csv.yaml" | tail -1)"; # echo "[INFO] CSV = ${CSV_FILE}"
 sed -r \
     `# for plugin & devfile registries, use internal Brew versions` \
     -e "s|registry.redhat.io/codeready-workspaces/(pluginregistry-rhel8:.+)|registry-proxy.engineering.redhat.com/rh-osbs/codeready-workspaces-\\1|g" \
@@ -136,13 +141,16 @@ sed -r \
 
 # 2. generation of digests already done as part of sync-che-olm-to-crw-olm.sh above
 
-# NOTE about openshift.versions field below: "v4.5,v4.6" is special. Do not change it. 
-# use backport=true for v4.5 support
+# NOTE about openshift.versions field below: "v4.6" is special, meaning 4.6+. 
+# Do not change it (unless we want to restrict CRW from being available on specific OCP versions (eg., v4.6,v4.8 would exclude support for v4.7)
 # See details in https://docs.engineering.redhat.com/display/CFC/Delivery
 
 # 3. revert to OSBS image refs, since digest pinning will automatically switch them to RHCC values
+CRW_OPERATOR="crw-2-rhel8-operator" # but in OSBS, want just operator
 sed -r \
     -e "s#(quay.io/crw/|registry.redhat.io/codeready-workspaces/)#registry-proxy.engineering.redhat.com/rh-osbs/codeready-workspaces-#g" \
+		`# use internal image for codeready-workspaces-operator, as codeready-workspaces-crw-2-rhel8-operator only exists in RHEC and Quay repos` \
+		-e "s#registry-proxy.engineering.redhat.com/rh-osbs/codeready-workspaces-${CRW_OPERATOR}#registry-proxy.engineering.redhat.com/rh-osbs/codeready-workspaces-operator#" \
     -i "${CSV_FILE}"
 METADATA='ENV SUMMARY="Red Hat CodeReady Workspaces ''' + SYNC_REPO + ''' container" \\\r
     DESCRIPTION="Red Hat CodeReady Workspaces ''' + SYNC_REPO + ''' container" \\\r
@@ -155,8 +163,8 @@ LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1 \\\r
       operators.operatorframework.io.bundle.channels.v1=latest \\\r
       operators.operatorframework.io.bundle.channel.default.v1=latest \\\r
       com.redhat.delivery.operator.bundle="true" \\\r
-      com.redhat.openshift.versions="v4.5,v4.6" \\\r
-      com.redhat.delivery.backport=true \\\r
+      com.redhat.openshift.versions="v4.6" \\\r
+      com.redhat.delivery.backport=false \\\r
       summary="$SUMMARY" \\\r
       description="$DESCRIPTION" \\\r
       io.k8s.description="$DESCRIPTION" \\\r
@@ -164,36 +172,41 @@ LABEL operators.operatorframework.io.bundle.mediatype.v1=registry+v1 \\\r
       io.openshift.tags="$PRODNAME,$COMPNAME" \\\r
       com.redhat.component="$PRODNAME-rhel8-$COMPNAME-container" \\\r
       name="$PRODNAME/$COMPNAME" \\\r
-      version="'$CRW_VERSION'" \\\r
+      version="''' + CRW_VERSION + '''" \\\r
       license="EPLv2" \\\r
       maintainer="Nick Boldt <nboldt@redhat.com>, Dmytro Nochevnov <dnochevn@redhat.com>" \\\r
       io.openshift.expose-services="" \\\r
       usage="" \r'
 
-echo -e "$METADATA" >> ${WORKSPACE}/targetdwn/Dockerfile
+echo -e "$METADATA" >> ${TARGET_DIR}/Dockerfile
 '''
 
-          // push changes in github to dist-git
-          util.updateBaseImages("${WORKSPACE}/targetdwn", MIDSTM_BRANCH, "--nocommit")
+          // don't commit yet, we'll do it later
+          util.updateBaseImages("${TARGET_DIR}", MIDSTM_BRANCH, "--nocommit")
+
+          // if anything changed, push changes in gh to dist-git
           sh '''#!/bin/bash -xe
-export KRB5CCNAME=/var/tmp/crw-build_ccache
 cd ${WORKSPACE}/targetdwn
-if [[ \$(git diff --name-only) ]]; then # file changed
-  git add Dockerfile ''' + SYNC_FILES_MID2DWN + '''
-  git commit -s -m "[sync] Update from ''' + SOURCE_REPO + ''' @ ''' + SOURCE_SHA + ''' + ''' + MIDSTM_REPO + ''' @ ''' + NEW_SHA_MID + '''" \
-    Dockerfile ''' + SYNC_FILES_MID2DWN + ''' || true
-  git push origin ''' + MIDSTM_BRANCH + '''
-  echo "[sync] Updated pkgs.devel @ \$(git rev-parse --short=4 HEAD) from ''' + SOURCE_REPO + ''' @ ''' + SOURCE_SHA + ''' + ''' + MIDSTM_REPO + ''' @ ''' + NEW_SHA_MID + '''"
+git add ''' + util.getCRWLongName(SYNC_REPO) + '''
+git update-index --refresh || true # ignore timestamp updates
+if [[ \$(git diff-index HEAD --) ]]; then # file changed
+  cd ''' + TARGET_DIR + '''
+  git add Dockerfile ''' + SYNC_FILES_MID2DWN + ''' || true
+  git commit -s -m "[sync] Update operator-metadata from ''' + SOURCE_REPO + ''' @ ''' + SOURCE_SHA + ''' + ''' + MIDSTM_REPO + ''' @ ''' + NEW_SHA_MID + '''" Dockerfile ''' + SYNC_FILES_MID2DWN + ''' || true
+  git push origin ''' + MIDSTM_BRANCH + ''' || true
+  NEW_SHA_DWN=\$(git rev-parse --short=4 HEAD) 
+  echo "[sync] Updated codeready-workspaces-images @ ${NEW_SHA_DWN} from ''' + SOURCE_REPO + ''' @ ''' + SOURCE_SHA + ''' + ''' + MIDSTM_REPO + ''' @ ''' + NEW_SHA_MID + '''"
 fi
-cd ..
 '''
-          NEW_SHA_DWN = util.getLastCommitSHA("${WORKSPACE}/targetdwn")
+
+          NEW_SHA_DWN = util.getLastCommitSHA("${TARGET_DIR}")
           println "Got NEW_SHA_DWN in targetdwn folder: " + NEW_SHA_DWN
+          currentBuild.description="Upstream sync done"
 
           if (NEW_SHA_MID.equals(OLD_SHA_MID) && NEW_SHA_DWN.equals(OLD_SHA_DWN) && !FORCE_BUILD.equals("true")) {
+            println "No changes upstream, nothing to commit"
             currentBuild.result='UNSTABLE'
           }
-
         } // with
       } // wrap
     } // stage
@@ -201,7 +214,7 @@ cd ..
 } // timeout
 
 // kick off get-sources-rhpkg-container-build_2.y job
-node(nodeLabel){ 
+node(nodeLabel) {
   stage ("Build container on ${nodeLabel}") {
     println "########################################################################################################"
     println "##  Build ${SYNC_REPO} container"
@@ -210,11 +223,12 @@ node(nodeLabel){
     def util = load "${WORKSPACE}/util.groovy"
     echo "currentBuild.result = " + currentBuild.result
     if (!currentBuild.result.equals("ABORTED") && !currentBuild.result.equals("FAILURE")) {
-      if (!NEW_SHA_MID.equals(OLD_SHA_MID) || !NEW_SHA_DWN.equals(OLD_SHA_DWN) || FORCE_BUILD == "true") {
+      if (!NEW_SHA_MID.equals(OLD_SHA_MID) || !NEW_SHA_DWN.equals(OLD_SHA_DWN) || FORCE_BUILD.equals("true")) {
+        JOB_BRANCH = util.getJobBranch(MIDSTM_BRANCH)
         build(
-              job: 'get-sources-rhpkg-container-build_' + CRW_VERSION,
-              wait: false,
-              propagate: false,
+              job: 'sync-to-downstream_' + JOB_BRANCH,
+              wait: true,
+              propagate: true,
               parameters: [
                 [
                   $class: 'StringParameterValue',
@@ -224,28 +238,22 @@ node(nodeLabel){
                 [
                   $class: 'StringParameterValue',
                   name: 'cause',
-                  value: "${SYNC_REPO}+respin+by+${BUILD_TAG}"
+                  value: SYNC_REPO + "+respin+by+${BUILD_TAG}"
                 ],
                 [
                   $class: 'StringParameterValue',
-                  name: 'GIT_BRANCH',
-                  value: "${MIDSTM_BRANCH}"
-                ],
-                [
-                  $class: 'StringParameterValue',
-                  name: 'GIT_PATHs',
-                  value: "${DWNSTM_REPO}"
-                ],
-                [
-                  $class: 'StringParameterValue',
-                  name: 'QUAY_REPO_PATHs',
-                  // SPECIAL CASE FOR operator-metadata (and operator)
-                  value: "crw-2-rhel8-" + util.getCRWShortName(SYNC_REPO)
+                  name: 'REPOS',
+                  value: util.getCRWLongName(SYNC_REPO)
                 ],
                 [
                   $class: 'StringParameterValue',
                   name: 'JOB_BRANCH',
-                  value: "${JOB_BRANCH}"
+                  value: JOB_BRANCH
+                ],
+                [
+                  $class: 'StringParameterValue',
+                  name: 'MIDSTM_BRANCH',
+                  value: MIDSTM_BRANCH
                 ],
                 [
                   $class: 'BooleanParameterValue',
@@ -255,14 +263,14 @@ node(nodeLabel){
                 [
                   $class: 'BooleanParameterValue',
                   name: 'SCRATCH',
-                  value: SCRATCH
+                  value: false
                 ]
               ]
         )
-        currentBuild.description="Brew build triggered"
+        currentBuild.description+="; Downstream sync job triggered"
       } else {
-        println "No changes upstream, nothing to build in brew!"
-        currentBuild.description="No Brew build"
+        println "No changes upstream, nothing to sync / build in brew!"
+        currentBuild.description+="; No sync or Brew build"
         currentBuild.result = 'UNSTABLE'
       }
     } else {
@@ -271,47 +279,3 @@ node(nodeLabel){
   } // stage
 } //node
 
-// kick off crwctl_2.y job
-node(nodeLabel){ 
-  stage ("Build crwctl on ${nodeLabel}") {
-    println "########################################################################################################"
-    println "##  Build crwctl ${JOB_BRANCH}"
-    println "########################################################################################################"
-    sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/'+ MIDSTM_BRANCH + '/product/util.groovy')
-    def util = load "${WORKSPACE}/util.groovy"
-    echo "currentBuild.result = " + currentBuild.result
-    if (!currentBuild.result.equals("ABORTED") && !currentBuild.result.equals("FAILURE")) {
-      if (!NEW_SHA_MID.equals(OLD_SHA_MID) || !NEW_SHA_DWN.equals(OLD_SHA_DWN) || FORCE_BUILD.equals("true")) {
-        build(
-              job: 'crwctl_' + JOB_BRANCH,
-              wait: false,
-              propagate: false,
-              parameters: [
-                [
-                  $class: 'StringParameterValue',
-                  name: 'token',
-                  value: "CI_BUILD"
-                ],
-                [
-                  $class: 'StringParameterValue',
-                  name: 'cause',
-                  value: "build+crwctl+for+operator+sync+from+${BUILD_TAG}"
-                ],
-                [
-                  $class: 'StringParameterValue',
-                  name: 'versionSuffix',
-                  value: "CI"
-                ]
-              ]
-        )
-        currentBuild.description+="; crwctl build triggered"
-      } else {
-        println "No changes upstream, nothing to rebuild in crwctl!"
-        currentBuild.description+="; no crwctl build"
-        currentBuild.result = 'UNSTABLE'
-      }
-    } else {
-      util.notifyBuildFailed()
-    } // if
-  } // stage
-} //node
diff --git a/crw-jenkins/jobs/CRW_CI/push-latest-container-to-quay_2.9.jenkinsfile b/crw-jenkins/jobs/CRW_CI/push-latest-container-to-quay_2.9.jenkinsfile
--- a/crw-jenkins/jobs/CRW_CI/push-latest-container-to-quay_2.9.jenkinsfile
+++ b/crw-jenkins/jobs/CRW_CI/push-latest-container-to-quay_2.9.jenkinsfile
@@ -21,13 +21,16 @@ def checkFailure(arrayLines,serverName,errorOccurred)
 def errorOccurred = ""
 @Field String DIFF_LATEST_IMAGES_QUAY_V_STORED = "trigger-update"
 
-def String nodeLabel = 'rhel8'
-timeout(30) {
+def String nodeLabel = 'rhel8||s390x-rhel8||ppc64le-rhel8'
+currentBuild.description="Copying " + CONTAINERS + "..."
+timeout(90) {
     node(nodeLabel) {
         sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/'+ MIDSTM_BRANCH + '/product/util.groovy')
         def util = load "${WORKSPACE}/util.groovy"
         try { 
             stage("Copy from OSBS to Quay") {
+                currentBuild.description="Copying: " + CONTAINERS.trim().replaceAll(" ",", ")
+
                 wrap([$class: 'TimestamperBuildWrapper']) {
                     cleanWs()
                     CRW_VERSION = util.getCrwVersion(MIDSTM_BRANCH)
@@ -44,11 +47,9 @@ timeout(30) {
                             script: 'curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/'+MIDSTM_BRANCH+'/product/getLatestImageTags.sh && chmod +x getLatestImageTags.sh',
                             returnStdout: true).trim().split( '\n' )
 
-                        currentBuild.description="Copying: " + CONTAINERS.trim().replaceAll(" ",", ")
-
                         def NEW_NVR = ""
                         parallel copy_to_quay: {
-                            sh('''#!/bin/bash -xe
+                            def statusCode = sh(script: '''#!/bin/bash -xe
 QUAY_REGISTRY="quay.io/crw/"
 QUAY_USER="crw+crwci"
 
@@ -64,10 +65,15 @@ for c in ''' + CONTAINERS.trim() + '''; do
     if [[ $c == "operator" ]] || [[ $c == "operator-metadata" ]]; then 
         d=codeready-workspaces-${c}
     fi 
-    ./getLatestImageTags.sh -c ${d} --osbs --pushtoquay="''' + CRW_VERSION + ''' ''' + FLOATING_QUAY_TAGS + '''" &
+    ./getLatestImageTags.sh -b ''' + MIDSTM_BRANCH + ''' -c ${d} --osbs --pushtoquay="''' + CRW_VERSION + ''' ''' + FLOATING_QUAY_TAGS + '''" &
 done
 wait
-                            ''')
+                            ''', returnStatus: true)
+                            if (statusCode > 0) {
+                                errorOccurred = errorOccurred + 'error pushing to quay\n'; 
+                                currentBuild.description+="; error pushing to quay!"
+                                currentBuild.result = 'FAILURE'
+                            }
                         }, 
                         nvr_check: {
                             NEW_NVR = sh (
@@ -106,8 +112,12 @@ ${WORKSPACE}/getTagForImage.sh $(cat ${WORKSPACE}/LATEST_IMAGES.nvr)  -s > ${WOR
                             "=================== QUAY v NVR ===================\n" + 
                             DIFF_LATEST_IMAGES_QUAY_V_NVR + '\n' + 
                             ' Failure!\n'
-                            currentBuild.description="Quay/Brew version mismatch!"
-                            currentBuild.result = 'FAILURE'
+                            currentBuild.description+="; Quay/Brew version mismatch"
+                            currentBuild.result = 'UNSTABLE'
+                            sh(script: '''#!/bin/bash -xe
+    ./getLatestImageTags.sh -b ''' + MIDSTM_BRANCH + ''' --osbs --pushtoquay="''' + CRW_VERSION + ''' ''' + FLOATING_QUAY_TAGS + '''"
+                            ''', returnStatus: true)
+                            currentBuild.description+="; all Quay images updated"
                         }
 
                         DIFF_LATEST_IMAGES_QUAY_V_STORED = sh (
@@ -146,14 +156,17 @@ node(nodeLabel){
     sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/'+ MIDSTM_BRANCH + '/product/util.groovy')
     def util = load "${WORKSPACE}/util.groovy"
     echo "currentBuild.result = " + currentBuild.result
-    if (!currentBuild.result.equals("ABORTED") && !currentBuild.result.equals("FAILED")) {
+    if (!currentBuild.result.equals("ABORTED") && !currentBuild.result.equals("FAILURE")) {
         CRW_VERSION = util.getCrwVersion(MIDSTM_BRANCH)
         println "CRW_VERSION = '" + CRW_VERSION + "'"
         JOB_BRANCH = util.getJobBranch(MIDSTM_BRANCH)
 
         // check if ${WORKSPACE}/LATEST_IMAGES.quay is different from stored LATEST_IMAGES
         // if LATEST_IMAGES files are different, run downstream job, if not, echo warning / set status yellow
-        if (!DIFF_LATEST_IMAGES_QUAY_V_STORED.equals("")) {
+        if (CONTAINERS.trim().equals("operator-metadata")) {
+            println "NOTE: Skip scheduling update-digests-in-registries-and-metadata for this update, as we have just updated operator-metadata."
+            currentBuild.description+="; update-digests-in-registries-and-metadata NOT triggered"
+        } else if (!DIFF_LATEST_IMAGES_QUAY_V_STORED.equals("")) {
             println "Scheduling update-digests-in-registries-and-metadata for this update:"
             println DIFF_LATEST_IMAGES_QUAY_V_STORED
             build(
@@ -173,14 +186,18 @@ node(nodeLabel){
                     ]
                 ]
             )
-            currentBuild.description=currentBuild.description+"; update-digests-in-registries-and-metadata triggered"
+            currentBuild.description+="; update-digests-in-registries-and-metadata triggered"
+        } else {
+            println "No changes to LATEST_IMAGES; no need to trigger update-digests-in-registries-and-metadata_" + CRW_VERSION
+            currentBuild.result = 'UNSTABLE'
+            currentBuild.description+="; update-digests-in-registries-and-metadata NOT triggered"
+        }
 
-        } else if (CONTAINERS.trim().equals("operator-metadata") || CONTAINERS.trim().matches(".*operator-metadata.*")) {
+        if (CONTAINERS.trim().equals("operator-metadata") || CONTAINERS.trim().matches(".*operator-metadata.*")) {
             // https://issues.redhat.com/browse/CRW-1564 if an update to operator-metadata, push new csv content into crw-images repo, 
             // in codeready-workspaces-operator-metadata-generated folder (outside where we sync from up->mid->down, as this should NOT
             // be synced to downstream or overwritten by upstream)
             util.installSkopeoFromContainer("")
-            sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/'+ MIDSTM_BRANCH + '/product/containerExtract.sh')
             SOURCE_REPO="redhat-developer/codeready-workspaces-images"
             println "####################################################################################################################"
             println "##  Clone and update github.com/${SOURCE_REPO}.git with latest Brew-generated CSV content (including pinned digests)"
@@ -190,22 +207,39 @@ node(nodeLabel){
                 util.bootstrap(CRW_KEYTAB)
                 util.cloneRepo("https://github.com/${SOURCE_REPO}.git", "${WORKSPACE}/sources", MIDSTM_BRANCH)
                 sh(script: '''#!/bin/bash -xe
-rm -fr /tmp/quay.io-crw-crw-2-rhel8-operator-metadata-''' + CRW_VERSION + '''-* || true
-chmod +x containerExtract.sh && ./containerExtract.sh quay.io/crw/crw-2-rhel8-operator-metadata:''' + CRW_VERSION + ''' || true
-rsync -zrlt /tmp/quay.io-crw-crw-2-rhel8-operator-metadata-''' + CRW_VERSION + '''-*/* \
-    ${WORKSPACE}/sources/codeready-workspaces-operator-metadata-generated/
-pushd ${WORKSPACE}/sources/ >/dev/null
-    git add codeready-workspaces-operator-metadata-generated || true
-    git commit -m "[brew] Publish CSV with generated digests" codeready-workspaces-operator-metadata-generated || true
-    git pull origin ''' + MIDSTM_BRANCH + ''' || true
-    git push origin ''' + MIDSTM_BRANCH + '''
-popd >/dev/null ''')
+curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/'''+ MIDSTM_BRANCH + '''/product/updateGeneratedOperatorMetadata.sh
+chmod +x updateGeneratedOperatorMetadata.sh
+./updateGeneratedOperatorMetadata.sh -b ''' + MIDSTM_BRANCH + ''' -t ''' + CRW_VERSION + ''' -s ${WORKSPACE}/sources
+''')
             }
-        } else {
-            println "No changes to LATEST_IMAGES; no need to trigger update-digests-in-registries-and-metadata_" + CRW_VERSION
-            currentBuild.result = 'UNSTABLE'
-            currentBuild.description=currentBuild.description+"; update-digests-in-registries-and-metadata NOT triggered"
-        } // if 2
+            currentBuild.description+="; operator-metadata-generated updated"
+
+            println "####################################################################################################################"
+            println "##  Check registry-proxy.engineering.redhat.com/rh-osbs/iib for latest operator-metadata ${CRW_VERSION}"
+            println "####################################################################################################################"
+            def statusCode = sh(script: '''#!/bin/bash -xe
+curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/''' + MIDSTM_BRANCH + '''/product/getLatestImageTags.sh
+chmod +x getLatestImageTags.sh
+NEW_OSBS_IMAGE=$(./getLatestImageTags.sh -b ${MIDSTM_BRANCH} --osbs -c codeready-workspaces-operator-metadata --tag ''' + CRW_VERSION + '''-)
+
+# registry-proxy.engineering.redhat.com/rh-osbs/codeready-workspaces-operator-metadata:2.9-2	registry-proxy.engineering.redhat.com/rh-osbs/iib:69346	v4.7
+curl -sSLk "https://datagrepper.engineering.redhat.com/raw?topic=/topic/VirtualTopic.eng.ci.redhat-container-image.index.built&delta=1728000&rows_per_page=99&contains=codeready-workspaces" | jq ".raw_messages[].msg.index | [.added_bundle_images[0], .index_image, .ocp_version] | @tsv" -r | sort -u | tail -20 > datagrepper.tsv.txt
+
+FOUND=$(grep "${NEW_OSBS_IMAGE}" datagrepper.tsv.txt)
+if [[ $FOUND ]]; then
+  echo $FOUND
+  rm -f datagrepper.tsv.txt
+else
+  echo "[ERROR] Could not find ${NEW_OSBS_IMAGE} in registry-proxy.engineering.redhat.com/rh-osbs/iib !"
+  echo '  curl -sSLk "https://datagrepper.engineering.redhat.com/raw?topic=/topic/VirtualTopic.eng.ci.redhat-container-image.index.built&delta=1728000&rows_per_page=99&contains=codeready-workspaces" | jq ".raw_messages[].msg.index | [.added_bundle_images[0], .index_image, .ocp_version] | @tsv" -r | sort -u | tail -20'
+  exit 1
+fi
+''', returnStatus: true)
+            if (statusCode > 0) {
+                currentBuild.result = 'FAILURE'
+                currentBuild.description+="; ERROR: rh-osbs/iib NOT updated!"
+            }
+        } // if metadata 
     } // if
   } // stage
 } //node
@@ -216,7 +250,7 @@ node(nodeLabel){
     sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/'+ MIDSTM_BRANCH + '/product/util.groovy')
     def util = load "${WORKSPACE}/util.groovy"
     echo "currentBuild.result = " + currentBuild.result
-    if (!currentBuild.result.equals("ABORTED") && !currentBuild.result.equals("FAILED")) {
+    if (!currentBuild.result.equals("ABORTED") && !currentBuild.result.equals("FAILURE")) {
         // if CONTAINERS contains theia
         println "Containers: " + CONTAINERS.trim()
         if (CONTAINERS.trim().equals("theia") || CONTAINERS.trim().matches(".*theia .*")) {
@@ -241,7 +275,7 @@ node(nodeLabel){
                     ]
                 ]
             )
-            currentBuild.description=currentBuild.description+"; crw-theia-akamai triggered"
+            currentBuild.description+="; crw-theia-akamai triggered"
         } // if 2
     } // if
   } // stage
