chore: [jobs] Update from codeready-workspaces/crw-jenkins @ b385
Signed-off-by: devstudio-release <nickboldt+devstudio-release@gmail.com>

diff --git a/crw-jenkins/jobs/CRW_CI/sync-to-downstream_2.x.jenkinsfile b/crw-jenkins/jobs/CRW_CI/sync-to-downstream_2.x.jenkinsfile
--- a/crw-jenkins/jobs/CRW_CI/sync-to-downstream_2.x.jenkinsfile
+++ b/crw-jenkins/jobs/CRW_CI/sync-to-downstream_2.x.jenkinsfile
@@ -17,6 +17,8 @@ def SOURCE_SHA=""
 def String nodeLabelAnyArch = 'rhel83||s390x-rhel8||ppc64le-rhel8'
 def String nodeLabelXArch='rhel83' // TODO switch to rhel84
 
+def Map tasks = [failFast: true]
+
 // prestage #1 for building lang servers - delete previous GitHub release if present
 timeout(120) {
   node(nodeLabelAnyArch){
@@ -50,7 +52,6 @@ timeout(120) {
 }//timeout
 
 // prestage #2 for building lang servers - create assets and publish to GH releases
-// TODO this could be run in a parallel() block to save time
 for (int i=0; i < SYNC_REPOS.size(); i++) {
   SYNC_REPOi=SYNC_REPOS[i]
   if (SYNC_REPOi?.trim()) { // filter out nullstring values
@@ -72,7 +73,6 @@ for (int i=0; i < SYNC_REPOS.size(); i++) {
       def List nodeLabels = nodeLabelString.tokenize("\n")
       nodeLabel=nodeLabelXArch // by default assume we're on x64
       for (int j=0; j < nodeLabels.size(); j++) {
-        print "NodeLabel[j]: " + nodeLabels[j]
         switch(nodeLabels[j]) {
           case "s390x":
             nodeLabel = "s390x-rhel8"
@@ -81,42 +81,53 @@ for (int i=0; i < SYNC_REPOS.size(); i++) {
             nodeLabel = "ppc64le-rhel8"
             break
         }
-        print "[" + (j+1) + "/" + nodeLabels.size() + "] Run on ${nodeLabel}"
-        timeout(120) {
-          node(nodeLabel){
-            stage("Build assets for " + SYNC_REPOi) {
-              withCredentials([
-                string(credentialsId:'crw_devstudio-release-token', variable: 'GITHUB_TOKEN'),
-                string(credentialsId: 'quay.io-crw-crwci_user_token', variable: 'QUAY_TOKEN'),
-                usernamePassword(credentialsId: 'registry.redhat.io_crw_bot', usernameVariable: 'CRW_BOT_USERNAME', passwordVariable: 'CRW_BOT_PASSWORD'),
-                file(credentialsId: 'crw_crw-build-keytab', variable: 'CRW_KEYTAB')
-              ]) {
-                sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/'+ MIDSTM_BRANCH + '/product/util.groovy')
-                def util = load "${WORKSPACE}/util.groovy"
-                cleanWs()
-                util.installHub("2.14.2", GOLANG_VERSION)
-                CSV_VERSION = util.getCSVVersion(MIDSTM_BRANCH)
-                println("[INFO] Using CSV version = " + CSV_VERSION)
-                util.loginToRegistries() // force log in to registries
-                util.cloneRepoWithBootstrap("https://github.com/${SOURCE_REPO}.git", "${WORKSPACE}/sources", MIDSTM_BRANCH, false)
-                sh('''#!/bin/bash -xe
-                  pushd sources/''' + SYNC_REPOi + '''
-                  if [[ -f get-sources.sh ]]; then 
-                    sudo setenforce 0 || true # disable selinux for podman builds
-                    ./get-sources.sh --publish-assets --nobuild -v ''' + CSV_VERSION + '''
-                  else 
-                    echo "[ERROR] Could not run get-sources.sh --publish-assets (for ''' + SYNC_REPOi + ''')"; exit 1
-                  fi
-                  popd
-                ''')
-              }//creds
-            }//stage
-          }//node
-        }//timeout
-      }//for
+        print "[" + (i+1) + "/" + SYNC_REPOS.size() + "] [" + (j+1) + "/" + nodeLabels.size() + "] " + 
+          "Create task to build: " + SYNC_REPOi + " " + nodeLabel + " assets" 
+        tasks[nodeLabels[i]] = { ->
+          timeout(120) {
+            node(nodeLabel){
+              stage("Build " + SYNC_REPOi + " " + nodeLabel + " assets") {
+                withCredentials([
+                  string(credentialsId:'crw_devstudio-release-token', variable: 'GITHUB_TOKEN'),
+                  string(credentialsId: 'quay.io-crw-crwci_user_token', variable: 'QUAY_TOKEN'),
+                  usernamePassword(credentialsId: 'registry.redhat.io_crw_bot', usernameVariable: 'CRW_BOT_USERNAME', passwordVariable: 'CRW_BOT_PASSWORD'),
+                  file(credentialsId: 'crw_crw-build-keytab', variable: 'CRW_KEYTAB')
+                ]) {
+                  sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/'+ MIDSTM_BRANCH + '/product/util.groovy')
+                  def util = load "${WORKSPACE}/util.groovy"
+                  cleanWs()
+                  util.installHub("2.14.2", GOLANG_VERSION)
+                  CSV_VERSION = util.getCSVVersion(MIDSTM_BRANCH)
+                  println("[INFO] Using CSV version = " + CSV_VERSION)
+                  util.loginToRegistries() // force log in to registries
+                  util.cloneRepoWithBootstrap("https://github.com/${SOURCE_REPO}.git", "${WORKSPACE}/sources", MIDSTM_BRANCH, false)
+                  sh('''#!/bin/bash -xe
+                    pushd sources/''' + SYNC_REPOi + '''
+                    if [[ -f get-sources.sh ]]; then 
+                      sudo setenforce 0 || true # disable selinux for podman builds
+                      ./get-sources.sh --publish-assets --nobuild -v ''' + CSV_VERSION + '''
+                    else 
+                      echo "[ERROR] Could not run get-sources.sh --publish-assets (for ''' + SYNC_REPOi + ''')"; exit 1
+                    fi
+                    popd
+                  ''')
+                }//creds
+              }//stage
+            }//node
+          }//timeout
+        }// tasks
+      }// for
+
+      stage("Builds") {
+        println "########################################################################################################"
+        println "##  Build assets for " + SYNC_REPOi
+        println "########################################################################################################"
+        parallel(tasks)
+      }
     }//if
   }//if not null
 }//for
+
 
 // NOTE: Yarn 2 + s390x = fail, so if build requires Yarn 2, don't run on s390x boxes, eg., REPOS.contains("-my-yarn2-project") ...
 timeout(600) {
@@ -148,13 +159,17 @@ timeout(600) {
             println "########################################################################################################"
             util.bootstrap(CRW_KEYTAB, true) // force bootstrapping again on each node, in case we haven't logged in to registries
             util.cloneRepoWithBootstrap("https://github.com/${SOURCE_REPO}.git", "${WORKSPACE}/sources", MIDSTM_BRANCH, false)
+
             CRW_VERSION = util.getCrwVersion(MIDSTM_BRANCH)
             JOB_BRANCH = util.getJobBranch(MIDSTM_BRANCH)
 
             // ensure static Dockerfiles have the correct version encoded in them
             util.updateDockerfileVersions("${WORKSPACE}/sources", MIDSTM_BRANCH, CRW_VERSION)
+
             // ensure static Dockerfiles have the latest oc and helm rpms installed
             if (REPOS.contains("-plugin-") || REPOS.contains("-stacks-")) { util.updateOCRpms(OPENSHIFT_CONTENT_SET_VERSION); }
+
+            // TODO this should be aligned to OPENSHIFT_CONTENT_SET_VERSION once there's a newer release
             if (REPOS.contains("plugin-kubernetes")) { util.updateHelmRpms("4.8"); }
 
             currentBuild.description=""
