chore: [jobs] Update from codeready-workspaces/crw-jenkins @ 29d6
Signed-off-by: devstudio-release <nickboldt+devstudio-release@gmail.com>

diff --git a/crw-jenkins/jobs/CRW_CI/sync-to-downstream_2.x.jenkinsfile b/crw-jenkins/jobs/CRW_CI/sync-to-downstream_2.x.jenkinsfile
--- a/crw-jenkins/jobs/CRW_CI/sync-to-downstream_2.x.jenkinsfile
+++ b/crw-jenkins/jobs/CRW_CI/sync-to-downstream_2.x.jenkinsfile
@@ -14,12 +14,106 @@ def OLD_SHA=""
 def NEW_SHA=""
 def SOURCE_SHA=""
 
-// NOTE: Yarn 2 + s390x = fail, so if build requires Yarn 2, don't run on s390x boxes, eg., REPOS.contains("-my-yarn2-project") ...
-def String nodeLabel = 'rhel83||s390x-rhel8||ppc64le-rhel8'
+def String nodeLabelAnyArch = 'rhel83||s390x-rhel8||ppc64le-rhel8'
+def String nodeLabelXArch='rhel83' // TODO switch to rhel84
 
+// prestage #1 for building lang servers - delete previous GitHub release if present
+timeout(120) {
+  node(nodeLabelAnyArch){
+    stage("Remove previous GitHub Release (if one exists)") {
+      withCredentials([
+        string(credentialsId:'crw_devstudio-release-token', variable: 'GITHUB_TOKEN')
+      ]) {
+        sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/'+ MIDSTM_BRANCH + '/product/util.groovy')
+        def util = load "${WORKSPACE}/util.groovy"
+        cleanWs()
+        util.installHub("2.14.2", GOLANG_VERSION)
+        CSV_VERSION = util.getCSVVersion(MIDSTM_BRANCH)
+        println("[INFO] Using CSV version = " + CSV_VERSION)
+        util.cloneRepoWithBootstrap("https://github.com/${SOURCE_REPO}.git", "${WORKSPACE}/sources", MIDSTM_BRANCH, false)
+        for (int i=0; i < SYNC_REPOS.size(); i++) {//actually use hub to remove release for each repo in SYNC_REPOs
+          sh('''#!/bin/bash -xe
+            pushd sources/''' + SYNC_REPOS[i] + '''
+            if [[ -f get-sources.sh ]]; then 
+              ./get-sources.sh --delete-assets --nobuild -v ''' + CSV_VERSION + '''
+            else 
+              echo "[ERROR] Could not run get-sources.sh!"; exit 1
+            fi
+            popd
+          ''')
+        }//for
+      }//creds
+    }//stage
+  }//node
+}//timeout
+
+// prestage #2 for building lang servers - create assets and publish to GH releases
+// TODO this could be run in a parallel() block to save time
+for (int i=0; i < SYNC_REPOS.size(); i++) {
+  if (REPOS.contains("-plugin-") || REPOS.contains("-stacks-") || REPOS.contains("-traefik") || REPOS.contains("-configbump")) {
+    nodeLabelString = ""
+    timeout(120) {
+      node(nodeLabelAnyArch){
+        stage("Determine Architectures to Build Assets on"){
+            sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/' + MIDSTM_BRANCH + '/product/util.groovy')
+            def util = load "${WORKSPACE}/util.groovy"
+            util.installYq()
+            nodeLabelString = sh( script: '''cat sources/''' + SYNC_REPOS[i] + '''/container.yaml | yq -r '.platforms.only[]' ''',
+              returnStdout: true).trim()
+        }
+      }//node
+    }//timeout
+    def List nodeLabels = nodeLabelString.tokenize("\n")
+    nodeLabel=nodeLabelXArch // by default assume we're on x64
+    for (int j=0; j < nodeLabels.size(); j++) {
+      print "NodeLabel[j]: " + nodeLabels[j]
+      switch(nodeLabels[j]) {
+        case "s390x":
+          nodeLabel = "s390x-rhel8"
+          break
+        case "ppc64le":
+          nodeLabel = "ppc64le-rhel8"
+          break
+      }
+      print "[" + (j+1) + "/" + nodeLabels.size() + "] Run on ${nodeLabel}"
+      timeout(120) {
+        node(nodeLabel){
+          stage("Build Assets for " + SYNC_REPOS[i]) {
+            withCredentials([
+              string(credentialsId:'crw_devstudio-release-token', variable: 'GITHUB_TOKEN'),
+              string(credentialsId: 'quay.io-crw-crwci_user_token', variable: 'QUAY_TOKEN'),
+              usernamePassword(credentialsId: 'registry.redhat.io_crw_bot', usernameVariable: 'CRW_BOT_USERNAME', passwordVariable: 'CRW_BOT_PASSWORD'),
+              file(credentialsId: 'crw_crw-build-keytab', variable: 'CRW_KEYTAB')
+            ]) {
+              sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/'+ MIDSTM_BRANCH + '/product/util.groovy')
+              def util = load "${WORKSPACE}/util.groovy"
+              cleanWs()
+              util.installHub("2.14.2", GOLANG_VERSION)
+              CSV_VERSION = util.getCSVVersion(MIDSTM_BRANCH)
+              println("[INFO] Using CSV version = " + CSV_VERSION)
+              util.cloneRepoWithBootstrap("https://github.com/${SOURCE_REPO}.git", "${WORKSPACE}/sources", MIDSTM_BRANCH, false)
+              sh('''#!/bin/bash -xe
+                pushd sources/''' + SYNC_REPOS[i] + '''
+                if [[ -f get-sources.sh ]]; then 
+                  sudo setenforce 0 || true # disable selinux for podman builds
+                  ./get-sources.sh --publish-assets --nobuild -v ''' + CSV_VERSION + '''
+                else 
+                  echo "[ERROR] Could not run get-sources.sh!"; exit 1
+                fi
+                popd
+              ''')
+            }//creds
+          }//stage
+        }//node
+      }//timeout
+    }//for
+  }//if
+}//for
+
+// NOTE: Yarn 2 + s390x = fail, so if build requires Yarn 2, don't run on s390x boxes, eg., REPOS.contains("-my-yarn2-project") ...
 timeout(600) {
-  node(nodeLabel) {
-    stage ("Sync repos on ${nodeLabel}") {
+  node(nodeLabelAnyArch) {
+    stage ("Sync repos on ${nodeLabelAnyArch}") {
       wrap([$class: 'TimestamperBuildWrapper']) {
         sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/' + MIDSTM_BRANCH + '/product/util.groovy')
         def util = load "${WORKSPACE}/util.groovy"
@@ -27,6 +121,7 @@ timeout(600) {
         currentBuild.description="${REPOS}<br/>Install skopeo, rhpkg, "
         util.installSkopeoFromContainer("")
         util.installRhpkg()
+        util.installHub("2.14.2", GOLANG_VERSION) // for get-sources.sh -> uploadAssetsToGHRelease.sh
         // install node and yarn if versions defined (eg., for theia-dev's generator tgz)
         if (util.globalVar({nodeVersion})?.trim() && util.globalVar({yarnVersion})?.trim()) {
           if (REPOS.contains("-theia-dev") || REPOS.contains("-dashboard")) { // need make, c++ for node-gyp
@@ -50,8 +145,8 @@ timeout(600) {
             // ensure static Dockerfiles have the correct version encoded in them
             util.updateDockerfileVersions("${WORKSPACE}/sources", MIDSTM_BRANCH, CRW_VERSION)
             // ensure static Dockerfiles have the latest oc and helm rpms installed
-            if (REPOS.contains("-plugin-") || REPOS.contains("-stacks-")) { util.updateOCRpms("4.8"); }
-            if (REPOS.contains("plugin-kubernetes")) { util.updateHelmRpms("4.8"); }
+            if (REPOS.contains("-plugin-") || REPOS.contains("-stacks-")) { util.updateOCRpms(OPENSHIFT_CONTENT_SET_VERSION); }
+            if (REPOS.contains("plugin-kubernetes")) { util.updateHelmRpms(OPENSHIFT_CONTENT_SET_VERSION); }
 
             currentBuild.description=""
             def QUAY_REPO_PATH=""
@@ -101,12 +196,11 @@ rm -f /tmp/rsync-excludes
                 sh('''#!/bin/bash -xe
                   export KRB5CCNAME=/var/tmp/crw-build_ccache
                   cd ${WORKSPACE}/targetdwn/''' + SYNC_REPOS[i] + '''
-                  if [[ -f get-sources.sh ]]; then 
-                    ./get-sources.sh -n -p ''' + JOB_BRANCH + '''
-                  elif [[ -f get-sources-jenkins.sh ]]; then # old name
-                    ./get-sources-jenkins.sh -n -p ''' + JOB_BRANCH + '''
+                  if [[ -f get-sources.sh ]]; then
+		     # TODO should this use -v CSV_VERSION instead of JOB_BRANCH?
+                    ./get-sources.sh --pull-assets --nobuild ''' + JOB_BRANCH + '''
                   else 
-                    echo "[ERROR] Could not run get-sources.sh or get-sources-jenkins.sh!"; exit 1
+                    echo "[ERROR] Could not run get-sources.sh!"; exit 1
                   fi
                   COMMIT_SHA="$(git log origin/''' + MIDSTM_BRANCH + '''..''' + MIDSTM_BRANCH + ''' --pretty=format:%H)"
                   COMMIT_MSG="$(git log origin/''' + MIDSTM_BRANCH + '''..''' + MIDSTM_BRANCH + ''' --pretty=format:%B)"
@@ -218,8 +312,8 @@ rm -f /tmp/rsync-excludes
 } // timeout
 
 // kick off crwctl_2.y job if operator or metadata were synced above 
-node(nodeLabel){ 
-  stage ("Build crwctl on ${nodeLabel}") {
+node(nodeLabelAnyArch){ 
+  stage ("Build crwctl on ${nodeLabelAnyArch}") {
     if (REPOS.contains("-operator-")) { 
       sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/'+ MIDSTM_BRANCH + '/product/util.groovy')
       def util = load "${WORKSPACE}/util.groovy"
