chore: [jobs] Update from codeready-workspaces/crw-jenkins @ ea6a
Signed-off-by: devstudio-release <nickboldt+devstudio-release@gmail.com>

diff --git a/crw-jenkins/jobs/CRW_CI/update-digests-in-metadata_2.16.jenkinsfile b/crw-jenkins/jobs/CRW_CI/update-digests-in-metadata_2.16.jenkinsfile
--- a/crw-jenkins/jobs/CRW_CI/update-digests-in-metadata_2.16.jenkinsfile
+++ b/crw-jenkins/jobs/CRW_CI/update-digests-in-metadata_2.16.jenkinsfile
@@ -4,26 +4,23 @@ import groovy.transform.Field
 
 // PARAMETERS for this pipeline:
     // MIDSTM_BRANCH
+    // CLEAN_ON_FAILURE = "true"
 
 def errorOccurred = false
-def String nodeLabel = 'rhel83||x86_64-rhel8||s390x-rhel8||ppc64le-rhel8'
+def String nodeLabel = 'x86_64-rhel8||s390x-rhel8||ppc64le-rhel8'
 timeout(120) {
     node(nodeLabel){ 
         try { 
             stage ("Check for updated images") {
                 wrap([$class: 'TimestamperBuildWrapper']) {
-                    withCredentials([string(credentialsId:'crw_devstudio-release-token', variable: 'GITHUB_TOKEN'),
-                        file(credentialsId: 'crw_crw-build-keytab', variable: 'CRW_KEYTAB')]) {
-
-                        sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/'+ MIDSTM_BRANCH + '/product/util.groovy')
-                        def util = load "${WORKSPACE}/util.groovy"
+                    withCredentials([string(credentialsId:'crw_devstudio-release-token', variable: 'GITHUB_TOKEN')]) {
+                        sh('curl -sSLO https://raw.githubusercontent.com/redhat-developer/codeready-workspaces/'+ MIDSTM_BRANCH + '/product/util2.groovy')
+                        def util = load "${WORKSPACE}/util2.groovy"
                         cleanWs()
-                        util.installSkopeoFromContainer("")
-                        util.installYq()
                         CRW_VERSION = util.getCrwVersion(MIDSTM_BRANCH)
                         println "CRW_VERSION = '" + CRW_VERSION + "'"
                         JOB_BRANCH = util.getJobBranch(MIDSTM_BRANCH)
-                        util.cloneRepoWithBootstrap("https://github.com/redhat-developer/codeready-workspaces.git", "${WORKSPACE}/crw", MIDSTM_BRANCH, false)
+                        util.cloneRepo("https://github.com/redhat-developer/codeready-workspaces.git", "${WORKSPACE}/crw", MIDSTM_BRANCH, false)
 
                         def NEW_IMAGES = sh (
                             script: "cd ${WORKSPACE}/crw/product && ./getLatestImageTags.sh -b ${MIDSTM_BRANCH} --quay --tag ${CRW_VERSION}- --hide | tee ${WORKSPACE}/crw/dependencies/LATEST_IMAGES.new",
@@ -48,33 +45,48 @@ cp ${WORKSPACE}/crw/dependencies/LATEST_IMAGES{,.prev}
 echo "============ LATEST_IMAGES.prev ============>"
 cat ${WORKSPACE}/crw/dependencies/LATEST_IMAGES.prev
 echo "<============ LATEST_IMAGES ============"
+NUM_IMAGES=$(cat ${WORKSPACE}/crw/dependencies/LATEST_IMAGES.prev | wc -l)
+if [[ NUM_IMAGES -lt 1 ]]; then 
+    echo "ERROR: dependencies/LATEST_IMAGES.prev file is empty!"
+    exit 1
+else 
+    echo "Found $NUM_IMAGES images in dependencies/LATEST_IMAGES.prev"
+fi
 '''
 
                         // compare new and curent images
                         def newSet = NEW_IMAGES as Set
                         // def currentSet = CURRENT_IMAGES as Set
                         def operatorBundleImage = newSet.find { it.contains("operator-bundle") } 
-                        def operatorMetadataImage = newSet.find { it.contains("operator-metadata") } 
                         // newSet.each { echo "New: $it" }
                         // currentSet.each { echo "Current: $it" }
                         sh '''#!/bin/bash -xe
 echo "============ LATEST_IMAGES.new 1 ============>"
 cat ${WORKSPACE}/crw/dependencies/LATEST_IMAGES.new
 echo "<============ LATEST_IMAGES.new 1 ============"
+NUM_IMAGES=$(cat ${WORKSPACE}/crw/dependencies/LATEST_IMAGES.new | wc -l)
+if [[ NUM_IMAGES -lt 1 ]]; then 
+    echo "ERROR: dependencies/LATEST_IMAGES.new file is empty!"
+    exit 1
+else 
+    echo "Found $NUM_IMAGES images in dependencies/LATEST_IMAGES.new"
+fi
 '''
 
-                        // don't report a diff when new operator-bundle or operator-metadata, or we'll never get out of this recursion loop; instead report new images (anything that will cause a new metadata image to be rebuilt)
+                        // don't report a diff when new operator-bundle, or we'll never get out of this recursion loop; instead report new images (anything that will cause a new bundle image to be rebuilt)
                         // ignore theia-dev 
-                        def DIFF_LATEST_IMAGES_ANY_BUT_BUNDLE_OR_METADATA = sh (script: '''
+                        def DIFF_LATEST_IMAGES_ANY_BUT_BUNDLE = sh (script: '''
 diff -u0 ${WORKSPACE}/crw/dependencies/LATEST_IMAGES.{prev,new} | \
-grep -E -v "@@|dependencies/LATEST_IMAGES|theia-dev|operator-bundle|operator-metadata" || true
+grep -E -v "@@|dependencies/LATEST_IMAGES|theia-dev|operator-bundle" | \
+sed -r -e "s@quay.io/crw/|:.+|-rhel8|\\n|\\r|^(-|\\+)@@g" | sort -uV || true
                         ''', returnStdout: true).trim()
 
-                        // check diff including operator bundle or metadata, in case we forgot to update metadata
+                        // check diff including operator bundle, in case we forgot to update
                         // ignore theia-dev
-                        def DIFF_LATEST_IMAGES_METADATA_ONLY = sh (script: '''
+                        def DIFF_LATEST_IMAGES_BUNDLE_ONLY = sh (script: '''
 diff -u0 ${WORKSPACE}/crw/dependencies/LATEST_IMAGES.{prev,new} | \
-grep -E -v "@@|dependencies/LATEST_IMAGES|theia-dev" | grep -E "operator-bundle|operator-metadata" || true
+grep -E -v "@@|dependencies/LATEST_IMAGES|theia-dev" | grep -E "operator-bundle" | \
+sed -r -e "s@quay.io/crw/|:.+|-rhel8|\\n|\\r|^(-|\\+)@@g" | sort -uV || true
                         ''', returnStdout: true).trim()
 
                         // define what to do when we are ready to push changes
@@ -96,43 +108,31 @@ grep -E -v "@@|dependencies/LATEST_IMAGES|theia-dev" | grep -E "operator-bundle|
 
                         currentBuild.description="Checking for changed images..."
 
-                        if (!DIFF_LATEST_IMAGES_METADATA_ONLY.equals("") && DIFF_LATEST_IMAGES_ANY_BUT_BUNDLE_OR_METADATA.equals("")) { 
-                            // no changes, but a newer metadata image exists
-                            currentBuild.description="New metadata image detected: commit changes to LATEST_IMAGES"
+                        if (!DIFF_LATEST_IMAGES_BUNDLE_ONLY.equals("") && DIFF_LATEST_IMAGES_ANY_BUT_BUNDLE.equals("")) { 
+                            // no changes, but a newer bundle image exists
+                            currentBuild.description="New bundle image detected: commit changes to LATEST_IMAGES"
                             echo currentBuild.description
-                            echo DIFF_LATEST_IMAGES_METADATA_ONLY
+                            echo DIFF_LATEST_IMAGES_BUNDLE_ONLY
 
                             sh COMMITCHANGES
                             currentBuild.result='UNSTABLE'
-                        } else if (DIFF_LATEST_IMAGES_ANY_BUT_BUNDLE_OR_METADATA.equals("")) { 
+                        } else if (DIFF_LATEST_IMAGES_ANY_BUT_BUNDLE.equals("")) { 
                             // no changes
                             currentBuild.description="No new images detected: nothing to do!"
                             echo currentBuild.description
                             currentBuild.result='UNSTABLE'
                         } else {
-                            currentBuild.description="Detected new images: rebuild operator-bundle and operator-metadata"
-                            listChangedImages=(DIFF_LATEST_IMAGES_ANY_BUT_BUNDLE_OR_METADATA).replaceAll("quay.io/crw/|:.+|-rhel8|crw-2|\n|\r|^(-|\\+)","").replaceAll("\\+",",").tokenize(',').unique()
-                            for (String imgChanged : listChangedImages) { currentBuild.description += "<br/>* " + imgChanged }
+                            currentBuild.description="Detected new images: rebuild operator-bundle<br/>* " + DIFF_LATEST_IMAGES_ANY_BUT_BUNDLE.replaceAll('\n',"<br/>* ")
                             echo currentBuild.description
-                            echo DIFF_LATEST_IMAGES_ANY_BUT_BUNDLE_OR_METADATA
+                            echo DIFF_LATEST_IMAGES_ANY_BUT_BUNDLE
 
-                            parallel metadata: {
-                                build(
-                                    job: 'crw-operator-metadata_' + JOB_BRANCH,
-                                    wait: true,
-                                    propagate: true,
-                                    parameters: [[$class: 'BooleanParameterValue', name: 'FORCE_BUILD', value: true]]
-                                )
-                            },
-                            bundle: {
-                                build(
-                                    job: 'crw-operator-bundle_' + JOB_BRANCH,
-                                    wait: true,
-                                    propagate: true,
-				    quietPeriod: 0,
-                                    parameters: [[$class: 'BooleanParameterValue', name: 'FORCE_BUILD', value: true]]
-                                )
-                            }
+                            build(
+                                job: 'crw-operator-bundle_' + JOB_BRANCH,
+                                wait: true,
+                                propagate: true,
+                                quietPeriod: 0,
+                                parameters: [[$class: 'BooleanParameterValue', name: 'FORCE_BUILD', value: true]]
+                            )
 
                             while (true) 
                             {
@@ -145,29 +145,18 @@ grep -E -v "@@|dependencies/LATEST_IMAGES|theia-dev" | grep -E "operator-bundle|
                                     echo "Operator bundle has been rebuilt!"
                                     break
                                 }
-                                def rebuiltOperatorMetadataImage = sh (
-                                script: "cd ${WORKSPACE}/crw/product && ./getLatestImageTags.sh -b ${MIDSTM_BRANCH} -c 'crw/crw-2-rhel8-operator-metadata' --quay --tag ${CRW_VERSION}- --hide",
-                                returnStdout: true
-                                ).trim()
-                                echo "${rebuiltOperatorMetadataImage}"
-                                if (rebuiltOperatorMetadataImage!=operatorMetadataImage) {
-                                    echo "Operator metadata has been rebuilt!"
-                                    break
-                                }
                                 sleep(time:120,unit:"SECONDS")
                             }
 
                             sh COMMITCHANGES
                         }
-                        archiveArtifacts fingerprint: false, artifacts:"crw/dependencies/LATEST_IMAGES*"
-                        
                     } // with
                 } // wrap
                 cleanWs(
                     cleanWhenSuccess: true,
                     cleanWhenUnstable: true,
                     cleanWhenNotBuilt: false,
-                    cleanWhenFailure: false,
+                    cleanWhenFailure: CLEAN_ON_FAILURE,
                     cleanWhenAborted: true,
                     deleteDirs: true,
                     disableDeferredWipeout: true,
