chore: [jobs] Update from codeready-workspaces/crw-jenkins @ 6fb8
Signed-off-by: devstudio-release <nickboldt+devstudio-release@gmail.com>

diff --git a/crw-jenkins/jobs/DS_CI/sync-to-downstream_3.x.jenkinsfile b/crw-jenkins/jobs/DS_CI/sync-to-downstream_3.x.jenkinsfile
--- a/crw-jenkins/jobs/DS_CI/sync-to-downstream_3.x.jenkinsfile
+++ b/crw-jenkins/jobs/DS_CI/sync-to-downstream_3.x.jenkinsfile
@@ -218,52 +218,65 @@ rm -f /tmp/rsync-excludes
 
                 // push to dist-git
                 sh('''#!/bin/bash -xe
-                  cd ${WORKSPACE}/targetdwn/''' + "${SYNC_REPOS[i]}" + '''
-                  git add Dockerfile get-sources.sh container.yaml || true
-                  git update-index --refresh || true # ignore timestamp updates
-                  if [[ \$(git diff-index HEAD --) ]]; then # file changed
-                    export KRB5CCNAME=/var/tmp/crw-build_ccache
-                    git add . -A -f
-                    git commit -s -m "ci: [mid2dwn] Sync from ''' + SOURCE_REPO + ''' @ ''' + SOURCE_SHA + '''"
-                    git push origin ''' + MIDSTM_BRANCH + ''' || true
-                  fi''')
+cd ${WORKSPACE}/targetdwn/''' + "${SYNC_REPOS[i]}" + '''
+git add Dockerfile get-sources.sh container.yaml || true
+git update-index --refresh || true # ignore timestamp updates
+if [[ \$(git diff-index HEAD --) ]]; then # file changed
+  export KRB5CCNAME=/var/tmp/crw-build_ccache
+  git add . -A -f
+  git commit -s -m "ci: [mid2dwn] Sync from ''' + SOURCE_REPO + ''' @ ''' + SOURCE_SHA + '''"
+  git push origin ''' + MIDSTM_BRANCH + ''' || true
+fi''')
 
                 // run get-sources to ensure we have the latest sources (in case we clobbered a previous run) and update source repo
                 sh('''#!/bin/bash -xe
-                  export KRB5CCNAME=/var/tmp/crw-build_ccache
-                  cd ${WORKSPACE}/targetdwn/''' + "${SYNC_REPOS[i]}" + '''
-                  if [[ -f get-sources.sh ]]; then
-                    ./get-sources.sh --pull-assets --nobuild -v ''' + CSV_VERSION + '''
-                  else 
-                    echo "[ERROR] Could not run get-sources.sh!"; exit 1
-                  fi
-                  COMMIT_SHA="$(git log origin/''' + MIDSTM_BRANCH + '''..''' + MIDSTM_BRANCH + ''' --pretty=format:%H)"
-                  COMMIT_MSG="$(git log origin/''' + MIDSTM_BRANCH + '''..''' + MIDSTM_BRANCH + ''' --pretty=format:%B)"
-                  if [ ! -z "$COMMIT_SHA" ] ; then
-                    for f in $(git diff-tree --no-commit-id --name-only -r "$COMMIT_SHA") ; do
-                      # check if the file/folder to copy has a valid parent
-                      if [[ "${f}" != "${f%/*}" ]] && [[ -n "${f%/*}" ]]; then 
-                        # create destination dir in midstream before copying files from downstream into there
-                        mkdir -p ${WORKSPACE}/sources/''' + "${SYNC_REPOS[i]}" + '''/${f%/*}
-                      fi
-                      cp ${f} ${WORKSPACE}/sources/''' + "${SYNC_REPOS[i]}" + '''/${f}
-                    done
-                    git pull origin ''' + MIDSTM_BRANCH + ''' || true
-                    git push origin ''' + MIDSTM_BRANCH + ''' || true
+export KRB5CCNAME=/var/tmp/crw-build_ccache
+cd ${WORKSPACE}/targetdwn/''' + "${SYNC_REPOS[i]}" + '''
+if [[ -f get-sources.sh ]]; then
+  ./get-sources.sh --pull-assets --nobuild -v ''' + CSV_VERSION + ''' | tee get-sources.sh.log.txt
+else 
+  echo "[ERROR] Could not run get-sources.sh!"; exit 1
+fi
+COMMIT_SHA="$(git log origin/''' + MIDSTM_BRANCH + '''..''' + MIDSTM_BRANCH + ''' --pretty=format:%H)"
+COMMIT_MSG="$(git log origin/''' + MIDSTM_BRANCH + '''..''' + MIDSTM_BRANCH + ''' --pretty=format:%B)"
+if [ ! -z "$COMMIT_SHA" ] ; then
+  for f in $(git diff-tree --no-commit-id --name-only -r "$COMMIT_SHA") ; do
+    # check if the file/folder to copy has a valid parent
+    if [[ "${f}" != "${f%/*}" ]] && [[ -n "${f%/*}" ]]; then 
+      # create destination dir in midstream before copying files from downstream into there
+      mkdir -p ${WORKSPACE}/sources/''' + "${SYNC_REPOS[i]}" + '''/${f%/*}
+    fi
+    cp ${f} ${WORKSPACE}/sources/''' + "${SYNC_REPOS[i]}" + '''/${f}
+  done
+  git pull origin ''' + MIDSTM_BRANCH + ''' || true
+  git push origin ''' + MIDSTM_BRANCH + ''' || true
 
-                    # update source repo with updates from running get-sources
-                    cd ${WORKSPACE}/sources/''' + "${SYNC_REPOS[i]}" + '''
-                    git add . -A -f
-                    git commit -m "$COMMIT_MSG" || true
-                    git pull origin ''' + MIDSTM_BRANCH + ''' || true
-                    git push origin ''' + MIDSTM_BRANCH + ''' || true
-                  fi
-                ''')
+  # update source repo with updates from running get-sources
+  cd ${WORKSPACE}/sources/''' + "${SYNC_REPOS[i]}" + '''
+  git add . -A -f
+  git commit -m "$COMMIT_MSG" || true
+  git pull origin ''' + MIDSTM_BRANCH + ''' || true
+  git push origin ''' + MIDSTM_BRANCH + ''' || true
+fi''')
 
                 NEW_SHA = util.getLastCommitSHA("${WORKSPACE}/targetdwn/${SYNC_REPOS[i]}")
                 println "Got NEW_SHA in targetdwn/${SYNC_REPOS[i]} folder: " + NEW_SHA
 
-                currentBuild.description+=" synced; "
+                // check for errors in log to add to the build desc
+                def buildLogErrors = sh(script: '''#!/bin/bash
+cd ${WORKSPACE}/targetdwn/''' + "${SYNC_REPOS[i]}" + '''
+if [[ -f get-sources.sh.log.txt ]]; then 
+  grep -A1 -E "FAIL - not in allowed" get-sources.sh.log.txt
+  rm -f get-sources.sh.log.txt
+fi
+''', returnStdout: true)
+                if (buildLogErrors?.trim()) {
+                  currentBuild.description+=" failed:<br/>" + buildLogErrors.trim().replaceAll("\n","<br/>")
+                  currentBuild.result = "FAILURE"
+                  util.notifyBuildFailed()
+                } else {
+                  currentBuild.description+=" synced; "
+                }
                 if (NEW_SHA != OLD_SHA || FORCE_BUILD == true || FORCE_BUILD.toString().equals("true")) {
                   QUAY_REPO_PATH=util.getDSShortName("${SYNC_REPOS[i]}") + "-rhel8"
                   // special cases for operator and bundle
@@ -274,81 +287,83 @@ rm -f /tmp/rsync-excludes
                     // devspaces-rhel8-operator
                     QUAY_REPO_PATH="devspaces-rhel8-" + util.getDSShortName("${SYNC_REPOS[i]}")
                   }
-                  println ("Trigger get-sources-rhpkg-container-build_" + JOB_BRANCH + " for ${QUAY_REPO_PATH} from containers/${SYNC_REPOS[i]} branch ${MIDSTM_BRANCH}, job branch ${JOB_BRANCH} ...")
-                  // kick off get-sources-rhpkg-container-build_2.y job
-                  jobPath='/job/DS_CI/job/get-sources-rhpkg-container-build_' + JOB_BRANCH
-	                final jobResult = build(
-                    job: jobPath.replaceAll("/job/","/"),
-                    wait: true,
-                    propagate: true,
-                    quietPeriod: 0,
-                    parameters: [
-                      [
-                        $class: 'StringParameterValue',
-                        name: 'token',
-                        value: "CI_BUILD"
-                      ],
-                      [
-                        $class: 'StringParameterValue',
-                        name: 'cause',
-                        value: QUAY_REPO_PATH + "+respin+by+${BUILD_TAG}"
-                      ],
-                      [
-                        $class: 'StringParameterValue',
-                        name: 'UPDATE_BASE_IMAGES_FLAGS',
-                        value: util.globalVar({UPDATE_BASE_IMAGES_FLAGS})
-                      ],
-                      [
-                        $class: 'StringParameterValue',
-                        name: 'nodeVersion',
-                        value: util.globalVar({nodeVersion})
-                      ],
-                      [
-                        $class: 'StringParameterValue',
-                        name: 'yarnVersion',
-                        value: util.globalVar({yarnVersion})
-                      ],
-                      [
-                        $class: 'StringParameterValue',
-                        name: 'MIDSTM_BRANCH',
-                        value: MIDSTM_BRANCH
-                      ],
-                      [
-                        $class: 'StringParameterValue',
-                        name: 'GIT_PATHs',
-                        value: "containers/${SYNC_REPOS[i]}"
-                      ],
-                      [
-                        $class: 'StringParameterValue',
-                        name: 'QUAY_REPO_PATHs',
-                        value: QUAY_REPO_PATH
-                      ],
-                      [
-                        $class: 'StringParameterValue',
-                        name: 'JOB_BRANCH',
-                        value: JOB_BRANCH
-                      ],
-                      [
-                        $class: 'BooleanParameterValue',
-                        name: 'FORCE_BUILD',
-                        value: true
-                      ],
-                      [
-                        $class: 'BooleanParameterValue',
-                        name: 'SCRATCH',
-                        value: false
-                      ],
-                      [
-                        $class: 'BooleanParameterValue',
-                        name: 'CLEAN_ON_FAILURE',
-                        value: CLEAN_ON_FAILURE
+                  if (!currentBuild.result.equals("ABORTED") && !currentBuild.result.equals("FAILURE") && !currentBuild.result.equals("UNSTABLE")) {
+                    println ("Trigger get-sources-rhpkg-container-build_" + JOB_BRANCH + " for ${QUAY_REPO_PATH} from containers/${SYNC_REPOS[i]} branch ${MIDSTM_BRANCH}, job branch ${JOB_BRANCH} ...")
+                    // kick off get-sources-rhpkg-container-build_2.y job
+                    jobPath='/job/DS_CI/job/get-sources-rhpkg-container-build_' + JOB_BRANCH
+                    final jobResult = build(
+                      job: jobPath.replaceAll("/job/","/"),
+                      wait: true,
+                      propagate: true,
+                      quietPeriod: 0,
+                      parameters: [
+                        [
+                          $class: 'StringParameterValue',
+                          name: 'token',
+                          value: "CI_BUILD"
+                        ],
+                        [
+                          $class: 'StringParameterValue',
+                          name: 'cause',
+                          value: QUAY_REPO_PATH + "+respin+by+${BUILD_TAG}"
+                        ],
+                        [
+                          $class: 'StringParameterValue',
+                          name: 'UPDATE_BASE_IMAGES_FLAGS',
+                          value: util.globalVar({UPDATE_BASE_IMAGES_FLAGS})
+                        ],
+                        [
+                          $class: 'StringParameterValue',
+                          name: 'nodeVersion',
+                          value: util.globalVar({nodeVersion})
+                        ],
+                        [
+                          $class: 'StringParameterValue',
+                          name: 'yarnVersion',
+                          value: util.globalVar({yarnVersion})
+                        ],
+                        [
+                          $class: 'StringParameterValue',
+                          name: 'MIDSTM_BRANCH',
+                          value: MIDSTM_BRANCH
+                        ],
+                        [
+                          $class: 'StringParameterValue',
+                          name: 'GIT_PATHs',
+                          value: "containers/${SYNC_REPOS[i]}"
+                        ],
+                        [
+                          $class: 'StringParameterValue',
+                          name: 'QUAY_REPO_PATHs',
+                          value: QUAY_REPO_PATH
+                        ],
+                        [
+                          $class: 'StringParameterValue',
+                          name: 'JOB_BRANCH',
+                          value: JOB_BRANCH
+                        ],
+                        [
+                          $class: 'BooleanParameterValue',
+                          name: 'FORCE_BUILD',
+                          value: true
+                        ],
+                        [
+                          $class: 'BooleanParameterValue',
+                          name: 'SCRATCH',
+                          value: false
+                        ],
+                        [
+                          $class: 'BooleanParameterValue',
+                          name: 'CLEAN_ON_FAILURE',
+                          value: CLEAN_ON_FAILURE
+                        ]
                       ]
-                    ]
-                  )
-                  jobLink=jobPath + "/" +  jobResult?.number?.toString()
-                  println("waiting for build(" + jobPath + ")")
-                  println("++> Job ${JENKINS_URL}${jobLink}/console completed.")
-                  currentBuild.description+=" <a href=${jobLink}/>" + (jobLink.replaceAll("/job/","/")) + "</a> triggered; " 
+                    )
+                    jobLink=jobPath + "/" +  jobResult?.number?.toString()
+                    println("waiting for build(" + jobPath + ")")
+                    println("++> Job ${JENKINS_URL}${jobLink}/console completed.")
+                    currentBuild.description+=" <a href=${jobLink}/>" + (jobLink.replaceAll("/job/","/")) + "</a> triggered; " 
+                  }
                 } else {
                   println "No changes upstream, nothing to commit for ${SYNC_REPOS[i]}"
                   currentBuild.description+=" no changes; "
