chore: [jobs] Update from codeready-workspaces/crw-jenkins @ d959a
Signed-off-by: devstudio-release <nickboldt+devstudio-release@gmail.com>

diff --git a/crw-jenkins/jobs/DS_CI/sync-to-downstream_3.11.jenkinsfile b/crw-jenkins/jobs/DS_CI/sync-to-downstream_3.11.jenkinsfile
--- a/crw-jenkins/jobs/DS_CI/sync-to-downstream_3.11.jenkinsfile
+++ b/crw-jenkins/jobs/DS_CI/sync-to-downstream_3.11.jenkinsfile
@@ -71,7 +71,8 @@ curl -sSLo- https://raw.githubusercontent.com/redhat-developer/devspaces-images/
               // prestage #1 for building lang servers - delete previous GitHub release if present
               sh('''#!/bin/bash -xe
 pushd sources/''' + SYNC_REPOi + '''
-if [[ -f get-sources.sh ]]; then 
+# TODO when we're full migrated to cachito, remove all references to get-sources.sh in midstream and downstream.
+if [[ -f get-sources.sh ]]; then
   ./get-sources.sh --delete-assets --nobuild -v ''' + CSV_VERSION + '''
 
   # in case API is running slow, sleep for a bit before trying to push files into the freshly created release
@@ -125,6 +126,7 @@ echo "<<<############### df -h before building #################"
                   util.cloneRepo("https://github.com/${SOURCE_REPO}.git", "sources", MIDSTM_BRANCH, false)
                   sh('''#!/bin/bash -xe
                     pushd sources/''' + SYNC_REPOi + '''
+                    # TODO when we're full migrated to cachito, remove all references to get-sources.sh in midstream and downstream.
                     if [[ -f get-sources.sh ]]; then
                       ./get-sources.sh --publish-assets --nobuild -v ''' + CSV_VERSION + '''
                     else
@@ -301,29 +303,10 @@ rm -f /tmp/rsync-excludes
               //    ref: e8b28394b00f6d320ec7a9b758875c674595ed58
               sh('''#!/bin/bash -x
 yaml=${WORKSPACE}/targetdwn/''' + "${SYNC_REPOS[i]}" + '''/container.yaml
-
+UCYS=updateContainerYamlSHAs.sh
+curl -sSLo /tmp/${UCYS} https://raw.githubusercontent.com/redhat-developer/devspaces/devspaces-3-rhel-8/product/${UCYS} && chmod +x /tmp/${UCYS}
 if [[ $(grep 'remote_sources:' ${yaml}) ]]; then
-  sed -i '/# must be full 40 char sha, matching regex/d' $yaml
-
-  repos=$(cat ${yaml} | yq -r '.remote_sources[].remote_source.repo')
-
-  for repo in $repos; do
-    if [[ $(echo $repo | grep 'devspaces-images') ]]; then
-      SHA=''' + SOURCE_SHA + '''
-    else
-      name=$(cat ${yaml} | yq ".remote_sources[]|select(.remote_source.repo==\\"$repo\\")" | yq ".name")
-      branchOrTag=$(curl -sSLo- https://raw.githubusercontent.com/redhat-developer/devspaces/devspaces-3-rhel-8/dependencies/job-config.json | jq -r ".Other[$name].\\"''' + JOB_BRANCH + '''\\"")
-      #Try branch first
-      SHA=$(git ls-remote $repo refs/heads/$branchOrTag | sed -r -e "s@(.+)\\t.+@\\1@g")
-
-      if [[ ! $SHA ]]; then
-        #Use tag
-        SHA=$(git ls-remote $repo refs/tags/$branchOrTag | sed -r -e "s@(.+)\\t.+@\\1@g")
-      fi
-    fi
-
-    sed -r -i -e "/.+repo: .+${repo##*/}.*/{n;s/ref: .*/ref: $SHA/}" $yaml
-  done
+  /tmp/${UCYS} -b "${MIDSTM_BRANCH}" "${yaml}"
 fi
 
 # for builds (like udi.groovy) where the upstream repo is devspaces-images, must configure 
@@ -345,7 +328,13 @@ cp ${yaml} ${WORKSPACE}/sources/''' + "${SYNC_REPOS[i]}" + '''/container.yaml
               // push to dist-git
               sh('''#!/bin/bash -xe
 cd ${WORKSPACE}/targetdwn/''' + "${SYNC_REPOS[i]}" + '''
-git add Dockerfile get-sources.sh container.yaml || true
+git add Dockerfile container.yaml || true
+
+# TODO when we're full migrated to cachito, remove all references to get-sources.sh in midstream and downstream.
+if [[ ! -f get-sources.sh ]]; then 
+  git rm get-sources.sh || true
+fi
+
 git update-index --refresh || true # ignore timestamp updates
 if [[ \$(git diff-index HEAD --) ]]; then # file changed
   export KRB5CCNAME=/var/tmp/devspaces-build_ccache
@@ -359,10 +348,11 @@ fi
               sh('''#!/bin/bash -xe
 export KRB5CCNAME=/var/tmp/devspaces-build_ccache
 cd ${WORKSPACE}/targetdwn/''' + "${SYNC_REPOS[i]}" + '''
+# TODO when we're full migrated to cachito, remove all references to get-sources.sh in midstream and downstream.
 if [[ -f get-sources.sh ]]; then
   ./get-sources.sh --pull-assets --nobuild -v ''' + CSV_VERSION + ''' | tee get-sources.sh.log.txt
-else 
-  echo "[ERROR] Could not run get-sources.sh!"; exit 1
+# else 
+#   echo "[ERROR] Could not run get-sources.sh!"; exit 1
 fi
 COMMIT_SHA="$(git log origin/''' + MIDSTM_BRANCH + '''..''' + MIDSTM_BRANCH + ''' --pretty=format:%H)"
 COMMIT_MSG="$(git log origin/''' + MIDSTM_BRANCH + '''..''' + MIDSTM_BRANCH + ''' --pretty=format:%B)"
@@ -393,6 +383,7 @@ fi
               // check for errors in log to add to the build desc
               def buildLogErrors = sh(script: '''#!/bin/bash
 cd ${WORKSPACE}/targetdwn/''' + "${SYNC_REPOS[i]}" + '''
+# TODO when we're full migrated to cachito, remove all references to get-sources.sh in midstream and downstream.
 if [[ -f get-sources.sh.log.txt ]]; then 
   grep -A1 -E "FAIL - not in allowed" get-sources.sh.log.txt
   rm -f get-sources.sh.log.txt
